# Generated by Django 5.2.17 on 2026-08-12 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='defuncion',
            name='organizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_registros', to='seguridad.organizacion', verbose_name='Organización'),
        ),
        migrations.AddField(
            model_name='fichavigilancia',
            name='organizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_registros', to='seguridad.organizacion', verbose_name='Organización'),
        ),
        migrations.AddField(
            model_name='nacimiento',
            name='organizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_registros', to='seguridad.organizacion', verbose_name='Organización'),
        ),
        migrations.CreateModel(
            name='ConfiguracionGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(blank=True, max_length=60, verbose_name='Estado por defecto')),
                ('municipio', models.CharField(blank=True, max_length=100, verbose_name='Municipio por defecto')),
                ('parroquia', models.CharField(blank=True, max_length=100, verbose_name='Parroquia por defecto')),
                ('establecimiento', models.CharField(blank=True, max_length=200, verbose_name='Establecimiento por defecto')),
                ('fecha_corte_cie11', models.DateField(verbose_name='Fecha de corte CIE-11')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('organizacion_activa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='seguridad.organizacion', verbose_name='Organización activa')),
            ],
            options={
                'verbose_name': 'Configuración general',
                'verbose_name_plural': 'Configuración general',
            },
        ),
    ]
