# Generated by Django 5.2.17 on 2026-09-16 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_cie10_origen'),
        ('registros', '0002_defuncion_organizacion_fichavigilancia_organizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='defuncion',
            name='cie10_legacy',
            field=models.CharField(blank=True, help_text='Código tal como estaba codificado en el sistema anterior; no se pierde.', max_length=20, verbose_name='Código CIE-10 original (legacy)'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='cie11_sugerido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalogos.cie11', verbose_name='CIE-11 sugerido (cross-walk)'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='codificacion_pendiente',
            field=models.BooleanField(db_index=True, default=False, help_text='El evento requiere CIE-11 y aún no tiene código resuelto: lo revisa el codificador.', verbose_name='Pendiente de codificación CIE-11'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='legacy_id',
            field=models.CharField(blank=True, db_index=True, max_length=40, verbose_name='ID legacy de origen'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='legacy_tabla',
            field=models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Tabla legacy de origen'),
        ),
        migrations.AddField(
            model_name='fichavigilancia',
            name='cie10_legacy',
            field=models.CharField(blank=True, help_text='Código tal como estaba codificado en el sistema anterior; no se pierde.', max_length=20, verbose_name='Código CIE-10 original (legacy)'),
        ),
        migrations.AddField(
            model_name='fichavigilancia',
            name='cie11_sugerido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalogos.cie11', verbose_name='CIE-11 sugerido (cross-walk)'),
        ),
        migrations.AddField(
            model_name='fichavigilancia',
            name='codificacion_pendiente',
            field=models.BooleanField(db_index=True, default=False, help_text='El evento requiere CIE-11 y aún no tiene código resuelto: lo revisa el codificador.', verbose_name='Pendiente de codificación CIE-11'),
        ),
        migrations.AddField(
            model_name='fichavigilancia',
            name='legacy_id',
            field=models.CharField(blank=True, db_index=True, max_length=40, verbose_name='ID legacy de origen'),
        ),
        migrations.AddField(
            model_name='fichavigilancia',
            name='legacy_tabla',
            field=models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Tabla legacy de origen'),
        ),
        migrations.AddField(
            model_name='nacimiento',
            name='cie10_legacy',
            field=models.CharField(blank=True, help_text='Código tal como estaba codificado en el sistema anterior; no se pierde.', max_length=20, verbose_name='Código CIE-10 original (legacy)'),
        ),
        migrations.AddField(
            model_name='nacimiento',
            name='cie11_sugerido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalogos.cie11', verbose_name='CIE-11 sugerido (cross-walk)'),
        ),
        migrations.AddField(
            model_name='nacimiento',
            name='codificacion_pendiente',
            field=models.BooleanField(db_index=True, default=False, help_text='El evento requiere CIE-11 y aún no tiene código resuelto: lo revisa el codificador.', verbose_name='Pendiente de codificación CIE-11'),
        ),
        migrations.AddField(
            model_name='nacimiento',
            name='legacy_id',
            field=models.CharField(blank=True, db_index=True, max_length=40, verbose_name='ID legacy de origen'),
        ),
        migrations.AddField(
            model_name='nacimiento',
            name='legacy_tabla',
            field=models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Tabla legacy de origen'),
        ),
    ]
