# Generated by Django 5.2.17 on 2026-09-24 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_defuncion_cie10_legacy_defuncion_cie11_sugerido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichavigilancia',
            name='lote_id',
            field=models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Lote de carga masiva'),
        ),
    ]
