# Generated by Django 5.2.17 on 2026-10-01 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0004_fichavigilancia_lote_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='defuncion',
            name='asistencia_medica',
            field=models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No'), ('IGNORADO', 'Ignorado')], default='', max_length=10, verbose_name='Asistencia médica'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='asistencia_parto',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Asistencia del parto'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='causa_antecedentes',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Causas antecedentes (texto)'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='cirugia',
            field=models.BooleanField(default=False, verbose_name='Tuvo alguna cirugía'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='correo_contacto',
            field=models.EmailField(blank=True, default='', max_length=150, verbose_name='Correo electrónico de contacto'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='declarante_cedula',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Cédula del declarante'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='declarante_nombres',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Apellidos y nombres del declarante'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='descripcion_cirugia',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Breve descripción de la cirugía'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='descripcion_hecho_violento',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Descripción del hecho violento'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='diagnostico_examen_cadaver',
            field=models.BooleanField(default=False, verbose_name='Diagnóstico: examen del cadáver'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='diagnostico_examen_laboratorio',
            field=models.BooleanField(default=False, verbose_name='Diagnóstico: examen de laboratorio'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='diagnostico_historia_clinica',
            field=models.BooleanField(default=False, verbose_name='Diagnóstico: historia clínica'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='diagnostico_interrogatorio_familiar',
            field=models.BooleanField(default=False, verbose_name='Diagnóstico: interrogatorio familiar o testigo'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='edad_gestacional_semanas',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Semanas de gestación'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='edad_ignorada',
            field=models.BooleanField(default=False, verbose_name='Edad ignorada'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='es_muerte_fetal',
            field=models.BooleanField(default=False, verbose_name='Es muerte fetal'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('SOLTERO', 'Soltero(a)'), ('CASADO', 'Casado(a)'), ('VIUDO', 'Viudo(a)'), ('DIVORCIADO', 'Divorciado(a)'), ('UNIDO', 'Unido(a)'), ('SEPARADO', 'Separado(a)')], default='', max_length=15, verbose_name='Estado civil'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='fecha_hecho_violento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha del hecho violento'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='fecha_registro',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de registro'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='fecha_ultima_cirugia',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de la última cirugía'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='folio_defuncion',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Folio del acta'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='gaceta',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Gaceta'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='hora_hecho_violento',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora del hecho violento'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='intervalo_enf_muerte',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Intervalo entre inicio y muerte'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='lugar_nacimiento',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Lugar de nacimiento'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='madre_apellidos',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Apellidos de la madre'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='madre_cedula',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Cédula de la madre'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='madre_embarazada',
            field=models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No'), ('IGNORADO', 'Ignorado')], default='', max_length=10, verbose_name='Estaba embarazada'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='madre_fecha_ultima_gesta',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de la última gesta'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='madre_nombres',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Nombres de la madre'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='madre_numero_gestas',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Número de gestas (madre)'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='madre_puerperio',
            field=models.CharField(blank=True, choices=[('NIUNA', 'No corresponde'), ('DENTRO42D', 'Dentro de 42 días'), ('DENTRO12M', 'Dentro de 12 meses'), ('IGNORADO', 'Ignorado')], default='', max_length=12, verbose_name='En puerperio de'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='manera_de_morir',
            field=models.CharField(blank=True, choices=[('ENFERMEDAD', 'Enfermedad'), ('ACCIDENTE', 'Accidente'), ('AGRESION', 'Agresión'), ('AUTOINFLIGIDA', 'Autoinfligida'), ('NO_DETERMINADA', 'No determinada'), ('ESTUDIO_FORENSE', 'Estudio forense')], default='', max_length=15, verbose_name='Manera de morir'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='matricula_mpps',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Matrícula MPPS del médico'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='nacimiento_exterior',
            field=models.BooleanField(default=False, verbose_name='Nacimiento en el exterior'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='nacionalidad',
            field=models.CharField(blank=True, choices=[('V', 'Venezolana'), ('E', 'Extranjera'), ('P', 'Pasaporte'), ('I', 'Ignorado'), ('O', 'Otra')], default='', max_length=1, verbose_name='Nacionalidad'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='numero_acta_defuncion',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Número del acta de defunción'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='ocupacion_lugar_trabajo',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Ocupación y lugar de trabajo'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='otros_estados_patologicos',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Otros estados patológicos (texto)'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='peso_nacer_gramos',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Peso al nacer (g)'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='profesion',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Profesión'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='registrador_civil_cedula',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Cédula del registrador civil'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='registrador_civil_nombres',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Apellidos y nombres del registrador civil'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='registro_civil_nombre',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Nombre del registro civil'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='residencia_habitual',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Dirección de residencia habitual'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='resolucion',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Resolución'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='sabe_leer_escribir',
            field=models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No'), ('IGNORADO', 'Ignorado')], default='', max_length=10, verbose_name='Sabe leer y escribir'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='segundo_apellido',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Segundo apellido'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='segundo_nombre',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Segundo nombre'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='tipo_embarazo',
            field=models.CharField(blank=True, choices=[('UNICO', 'Único'), ('MULTIPLE', 'Múltiple')], default='', max_length=10, verbose_name='Tipo de embarazo'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='tipo_parto',
            field=models.CharField(blank=True, choices=[('VAGINAL', 'Vaginal'), ('CESAREA', 'Cesárea'), ('INSTRUMENTAL', 'Instrumental'), ('OTRO', 'Otro')], default='', max_length=12, verbose_name='Tipo de parto'),
        ),
    ]
