# Generated by Django 5.2.17 on 2026-10-02 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0005_defuncion_ev14'),
        ('territorio', '0003_asic_comunidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='nacimiento',
            name='certificador_cedula',
            field=models.CharField(blank=True, max_length=20, verbose_name='Cédula del responsable de la certificación'),
        ),
        migrations.AddField(
            model_name='nacimiento',
            name='certificador_matricula_mpps',
            field=models.CharField(blank=True, max_length=30, verbose_name='Nº MSDS del responsable'),
        ),
        migrations.AddField(
            model_name='nacimiento',
            name='certificador_nombres',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nombre del responsable de la certificación'),
        ),
        migrations.AddField(
            model_name='nacimiento',
            name='director_establecimiento',
            field=models.CharField(blank=True, max_length=200, verbose_name='Director del establecimiento'),
        ),
        migrations.AddField(
            model_name='nacimiento',
            name='fecha_emision',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de emisión'),
        ),
        migrations.AddField(
            model_name='nacimiento',
            name='madre_nacionalidad',
            field=models.CharField(blank=True, choices=[('V', 'Venezolana'), ('E', 'Extranjera'), ('P', 'Pasaporte'), ('I', 'Sin información'), ('O', 'Otra identificación')], max_length=1, verbose_name='Nacionalidad de la madre'),
        ),
        migrations.AddField(
            model_name='nacimiento',
            name='madre_pasaporte',
            field=models.CharField(blank=True, max_length=20, verbose_name='Nº de pasaporte u otra identificación de la madre'),
        ),
        migrations.AddField(
            model_name='nacimiento',
            name='madre_residencia',
            field=models.CharField(blank=True, choices=[('V', 'Venezuela'), ('E', 'Exterior'), ('I', 'Sin información')], max_length=1, verbose_name='Residencia habitual de la madre'),
        ),
        migrations.AddField(
            model_name='nacimiento',
            name='madre_residencia_comunidad',
            field=models.ForeignKey(blank=True, help_text='Nivel COMUNIDAD. Es el territorio de la madre, no el del establecimiento.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nacimientos_madre_comunidad', to='territorio.divisionterritorial', verbose_name='Comunidad de residencia de la madre'),
        ),
        migrations.AddField(
            model_name='nacimiento',
            name='madre_residencia_direccion',
            field=models.CharField(blank=True, max_length=250, verbose_name='Dirección de residencia de la madre'),
        ),
        migrations.AddField(
            model_name='nacimiento',
            name='madre_residencia_pais',
            field=models.CharField(blank=True, max_length=80, verbose_name='País de residencia de la madre'),
        ),
        migrations.AddField(
            model_name='nacimiento',
            name='madre_residencia_parroquia',
            field=models.ForeignKey(blank=True, help_text='Nivel PARROQUIA. Es el territorio de la madre, no el del establecimiento.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nacimientos_madre_parroquia', to='territorio.divisionterritorial', verbose_name='Parroquia de residencia de la madre'),
        ),
        migrations.AddField(
            model_name='nacimiento',
            name='nino_apellidos',
            field=models.CharField(blank=True, max_length=150, verbose_name='Apellidos del recién nacido'),
        ),
        migrations.AddField(
            model_name='nacimiento',
            name='nino_nombres',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nombres del recién nacido'),
        ),
        migrations.AddField(
            model_name='nacimiento',
            name='numero_historia_clinica',
            field=models.CharField(blank=True, max_length=30, verbose_name='Nº de historia clínica'),
        ),
        migrations.AddField(
            model_name='nacimiento',
            name='numero_planilla',
            field=models.CharField(blank=True, max_length=30, verbose_name='Nº de la planilla impresa'),
        ),
        migrations.AddField(
            model_name='nacimiento',
            name='padre_nacionalidad',
            field=models.CharField(blank=True, choices=[('V', 'Venezolana'), ('E', 'Extranjera'), ('P', 'Pasaporte'), ('I', 'Sin información'), ('O', 'Otra identificación')], max_length=1, verbose_name='Nacionalidad del padre'),
        ),
        migrations.AddField(
            model_name='nacimiento',
            name='padre_pasaporte',
            field=models.CharField(blank=True, max_length=20, verbose_name='Nº de pasaporte u otra identificación del padre'),
        ),
        migrations.AddField(
            model_name='nacimiento',
            name='padre_residencia',
            field=models.CharField(blank=True, choices=[('V', 'Venezuela'), ('E', 'Exterior'), ('I', 'Sin información')], max_length=1, verbose_name='Residencia habitual del padre'),
        ),
        migrations.AddField(
            model_name='nacimiento',
            name='padre_residencia_comunidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nacimientos_padre_comunidad', to='territorio.divisionterritorial', verbose_name='Comunidad de residencia del padre'),
        ),
        migrations.AddField(
            model_name='nacimiento',
            name='padre_residencia_direccion',
            field=models.CharField(blank=True, max_length=250, verbose_name='Dirección de residencia del padre'),
        ),
        migrations.AddField(
            model_name='nacimiento',
            name='padre_residencia_pais',
            field=models.CharField(blank=True, max_length=80, verbose_name='País de residencia del padre'),
        ),
        migrations.AddField(
            model_name='nacimiento',
            name='padre_residencia_parroquia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nacimientos_padre_parroquia', to='territorio.divisionterritorial', verbose_name='Parroquia de residencia del padre'),
        ),
        migrations.AddField(
            model_name='nacimiento',
            name='tipo_numero_certificado',
            field=models.CharField(blank=True, choices=[('COMPLETO', 'Completo'), ('HISTORICO', 'Histórico')], help_text='El formulario ofrece un número Completo u Histórico en el certificado impreso.', max_length=10, verbose_name='Tipo del nº en el certificado'),
        ),
        migrations.AlterField(
            model_name='nacimiento',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('I', 'Hermafrodita'), ('N', 'Sin información')], default='F', max_length=1, verbose_name='Sexo'),
        ),
    ]
