# Generated by Django 5.2.17 on 2026-10-03 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0006_nacimiento_ev25'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuraciongeneral',
            name='detectar_meses_degradados',
            field=models.BooleanField(default=True, help_text='Avisa cuando un mes tiene muchos menos registros de lo normal.', verbose_name='Detectar meses degradados'),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='factor_mes_degradado',
            field=models.FloatField(default=0.4, help_text='Cuánto del nivel normal puede bajar un mes antes de avisar (0 a 1).', verbose_name='Factor de mes degradado'),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='min_meses_historia',
            field=models.PositiveSmallIntegerField(default=12, help_text='Meses normales que se usan como referencia para comparar.', verbose_name='Meses de historia para la mediana'),
        ),
    ]
