# Generated by Django 5.2.17 on 2026-10-11 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0007_configuraciongeneral_detectar_meses_degradados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='defuncion',
            name='area_ocurrencia',
            field=models.CharField(blank=True, choices=[('RESIDENCIAL', 'Residencial'), ('DEPORTE', 'Área de deporte y atletismo'), ('COMERCIO', 'Comercio y áreas de servicio'), ('ESCUELAS', 'Instalación o área pública / escuelas'), ('CALLES', 'Calles o carreteras'), ('GRANJA', 'Granja'), ('INDUSTRIAL', 'Área industrial o de construcción'), ('OTRO', 'Otro')], default='', max_length=15, verbose_name='Área donde ocurrió la muerte'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='cargo_medico',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Cargo del médico responsable'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='causa_aplicando_reglas',
            field=models.TextField(blank=True, default='', verbose_name='Causa aplicando las reglas de clasificación'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='causa_descrita_medico',
            field=models.TextField(blank=True, default='', verbose_name='Causa de muerte descrita por el médico'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='causa_primera_parte',
            field=models.TextField(blank=True, default='', verbose_name='Causa — primera parte'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='causa_segunda_parte',
            field=models.TextField(blank=True, default='', verbose_name='Causa — segunda parte'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='codigo_comunidad',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Código de la comunidad'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='declarante_nacionalidad',
            field=models.CharField(blank=True, choices=[('V', 'Venezolana'), ('E', 'Extranjera'), ('P', 'Pasaporte'), ('I', 'Ignorado'), ('O', 'Otra')], default='', max_length=1, verbose_name='Tipo de documento del declarante'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='destino_cadaver',
            field=models.CharField(blank=True, choices=[('INHUMACION', 'Inhumación'), ('CREMACION', 'Cremación')], default='', max_length=12, verbose_name='Destino del cadáver'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='diagnostico_otro',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Diagnóstico confirmado por otro medio'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='direccion_medico',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Dirección del médico responsable'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='edad',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Edad del fallecido; la unidad la indica edad_unidad.', null=True, verbose_name='Edad'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='edad_unidad',
            field=models.CharField(blank=True, choices=[('ANIOS', 'Años'), ('MESES', 'Meses'), ('DIAS', 'Días')], default='', max_length=6, verbose_name='Unidad de la edad'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='etnia',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Etnia'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='fertil_abortos',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Abortos'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='fertil_contribuyo_muerte',
            field=models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No'), ('IGNORADO', 'Ignorado')], default='', max_length=10, verbose_name='La gestación contribuyó a la muerte'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='fertil_estaba_embarazada',
            field=models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No'), ('IGNORADO', 'Ignorado')], default='', max_length=10, verbose_name='Estaba embarazada'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='fertil_fecha_ultima_gesta',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de la última gesta'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='fertil_muertes_fetales',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Muertes fetales'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='fertil_nacidos_fallecidos',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Nacidos vivos fallecidos'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='fertil_nacidos_vivos',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Nacidos vivos (historia obstétrica)'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='fertil_numero_gestas',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Nº de gestas (mujer en edad fértil)'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='fertil_puerperio',
            field=models.CharField(blank=True, choices=[('NIUNA', 'No corresponde'), ('DENTRO42D', 'Dentro de 42 días'), ('DENTRO12M', 'Dentro de 12 meses'), ('IGNORADO', 'Ignorado')], default='', max_length=12, verbose_name='En puerperio de'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='nacimiento_entidad',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Entidad federal de nacimiento'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='nacimiento_pais',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='País de nacimiento (exterior)'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='numero_permiso',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Nº de permiso de inhumación'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='padre_fallecido_cedula',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Documento del padre del fallecido'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='padre_fallecido_nombres',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Padre del fallecido (apellidos y nombres)'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='partida_acta',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Acta de la partida de nacimiento'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='partida_folio',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Folio de la partida de nacimiento'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='partida_libro',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Libro de la partida de nacimiento'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='partida_tomo',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Tomo de la partida de nacimiento'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='registrador_civil_nacionalidad',
            field=models.CharField(blank=True, choices=[('V', 'Venezolana'), ('E', 'Extranjera'), ('P', 'Pasaporte'), ('I', 'Ignorado'), ('O', 'Otra')], default='', max_length=1, verbose_name='Tipo de documento del registrador civil'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='registro_civil_entidad',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Entidad del registro civil'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='sitio_ocurrencia',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Sitio donde ocurrió la muerte'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='telefono_medico',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Teléfono del médico responsable'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='tipo_certificacion',
            field=models.CharField(blank=True, choices=[('MEDICA', 'Médica'), ('NO_MEDICA', 'No médica'), ('OTRO', 'Otra')], default='', max_length=15, verbose_name='Tipo de certificación'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='ubicacion_geografica',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Ubicación geográfica'),
        ),
    ]
