# Generated by Django 5.2.17 on 2026-10-11 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0008_defuncion_area_ocurrencia_defuncion_cargo_medico_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='defuncion',
            name='codificado_en',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Codificado en'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='codificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Codificado por'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='sugerencia_codigo',
            field=models.CharField(blank=True, default='', help_text='Código propuesto por el motor de sugerencias (catálogo CIE local).', max_length=64, verbose_name='Código CIE sugerido'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='sugerencia_en',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Sugerido en'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='sugerencia_json',
            field=models.JSONField(blank=True, null=True, verbose_name='Detalle de la sugerencia'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='sugerencia_origen',
            field=models.CharField(blank=True, choices=[('', '—'), ('CATALOGO', 'Catálogo CIE'), ('IA', 'IA'), ('MANUAL', 'Manual')], default='', max_length=10, verbose_name='Origen de la sugerencia'),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='sugerencia_titulo',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Título del código sugerido'),
        ),
        migrations.AddField(
            model_name='fichavigilancia',
            name='codificado_en',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Codificado en'),
        ),
        migrations.AddField(
            model_name='fichavigilancia',
            name='codificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Codificado por'),
        ),
        migrations.AddField(
            model_name='fichavigilancia',
            name='sugerencia_codigo',
            field=models.CharField(blank=True, default='', help_text='Código propuesto por el motor de sugerencias (catálogo CIE local).', max_length=64, verbose_name='Código CIE sugerido'),
        ),
        migrations.AddField(
            model_name='fichavigilancia',
            name='sugerencia_en',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Sugerido en'),
        ),
        migrations.AddField(
            model_name='fichavigilancia',
            name='sugerencia_json',
            field=models.JSONField(blank=True, null=True, verbose_name='Detalle de la sugerencia'),
        ),
        migrations.AddField(
            model_name='fichavigilancia',
            name='sugerencia_origen',
            field=models.CharField(blank=True, choices=[('', '—'), ('CATALOGO', 'Catálogo CIE'), ('IA', 'IA'), ('MANUAL', 'Manual')], default='', max_length=10, verbose_name='Origen de la sugerencia'),
        ),
        migrations.AddField(
            model_name='fichavigilancia',
            name='sugerencia_titulo',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Título del código sugerido'),
        ),
        migrations.AddField(
            model_name='nacimiento',
            name='codificado_en',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Codificado en'),
        ),
        migrations.AddField(
            model_name='nacimiento',
            name='codificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Codificado por'),
        ),
        migrations.AddField(
            model_name='nacimiento',
            name='sugerencia_codigo',
            field=models.CharField(blank=True, default='', help_text='Código propuesto por el motor de sugerencias (catálogo CIE local).', max_length=64, verbose_name='Código CIE sugerido'),
        ),
        migrations.AddField(
            model_name='nacimiento',
            name='sugerencia_en',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Sugerido en'),
        ),
        migrations.AddField(
            model_name='nacimiento',
            name='sugerencia_json',
            field=models.JSONField(blank=True, null=True, verbose_name='Detalle de la sugerencia'),
        ),
        migrations.AddField(
            model_name='nacimiento',
            name='sugerencia_origen',
            field=models.CharField(blank=True, choices=[('', '—'), ('CATALOGO', 'Catálogo CIE'), ('IA', 'IA'), ('MANUAL', 'Manual')], default='', max_length=10, verbose_name='Origen de la sugerencia'),
        ),
        migrations.AddField(
            model_name='nacimiento',
            name='sugerencia_titulo',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Título del código sugerido'),
        ),
    ]
