# Generated by Django 5.2.17 on 2026-10-11 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0009_defuncion_codificado_en_defuncion_codificado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nacimiento',
            name='fecha_registro',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de inscripción'),
        ),
        migrations.AddField(
            model_name='nacimiento',
            name='madre_ocupacion',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Ocupación de la madre'),
        ),
        migrations.AddField(
            model_name='nacimiento',
            name='nombre_persona_atendio',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Apellidos y nombres de quien atendió el parto'),
        ),
        migrations.AddField(
            model_name='nacimiento',
            name='padre_ocupacion',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Ocupación del padre'),
        ),
        migrations.AddField(
            model_name='nacimiento',
            name='persona_atendio_parto',
            field=models.CharField(blank=True, choices=[('MEDICO', 'Médico'), ('ENFERMERA', 'Enfermera'), ('PARTERA', 'Partera'), ('COMADRONA', 'Comadrona'), ('OTRO', 'Otro')], default='', max_length=15, verbose_name='Persona que atendió el parto'),
        ),
        migrations.AddField(
            model_name='nacimiento',
            name='registrador_civil_cedula',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Cédula del registrador civil'),
        ),
        migrations.AddField(
            model_name='nacimiento',
            name='registrador_civil_nombres',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Apellidos y nombres del registrador civil'),
        ),
        migrations.AddField(
            model_name='nacimiento',
            name='registro_civil_nombre',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Nombre del registro civil'),
        ),
    ]
