# Generated by Django 5.2.17 on 2026-09-28 23:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seguridad', '0003_alter_perfil_rol'),
        ('vigilancia', '0002_consolidadosemanal_legacy_documento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConciliacionENO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.SmallIntegerField(db_index=True, verbose_name='Año')),
                ('semana', models.SmallIntegerField(db_index=True, verbose_name='Semana epidemiológica')),
                ('tipo', models.CharField(choices=[('MORBILIDAD', 'Morbilidad'), ('MORTALIDAD', 'Mortalidad')], max_length=10, verbose_name='Tipo')),
                ('legado_enfermedad_id', models.BigIntegerField(db_index=True, verbose_name='ID enfermedad legacy')),
                ('legado_enfermedad_codigo', models.CharField(blank=True, max_length=30, verbose_name='Código legacy')),
                ('legado_enfermedad_nombre', models.CharField(blank=True, max_length=300, verbose_name='Enfermedad legacy')),
                ('es_pseudo_total', models.BooleanField(default=False, help_text="Filas 'TOTAL DE PACIENTES...' del catálogo legacy: no son enfermedades.", verbose_name='Es fila de total')),
                ('cantidad_centros', models.PositiveIntegerField(default=1, verbose_name='Centros legacy')),
                ('colision', models.BooleanField(default=False, help_text='Más de un establecimiento legacy consolidó en esta misma organización.', verbose_name='Varios centros en la misma organización')),
                ('crudo_h', models.IntegerField(default=0, verbose_name='Casos crudos hombres')),
                ('crudo_m', models.IntegerField(default=0, verbose_name='Casos crudos mujeres')),
                ('sisv_h', models.IntegerField(default=0, verbose_name='Casos SISV hombres')),
                ('sisv_m', models.IntegerField(default=0, verbose_name='Casos SISV mujeres')),
                ('diferencia_h', models.IntegerField(default=0, verbose_name='Diferencia hombres')),
                ('diferencia_m', models.IntegerField(default=0, verbose_name='Diferencia mujeres')),
                ('estado', models.CharField(choices=[('CUADRA', 'Cuadra'), ('DIFERENCIA', 'Diferencia'), ('SOLO_CRUDO', 'Solo en el crudo'), ('SOLO_SISV', 'Solo en SISV'), ('EXCLUIDO_EN_ETL', 'Excluido por diseño del ETL')], db_index=True, max_length=16, verbose_name='Estado')),
                ('resolucion', models.CharField(choices=[('CONCILIADO', 'Conciliado'), ('CENTRO_SIN_ORG', 'Centro sin organización'), ('CENTRO_SIN_ORG_Y_EVENTO_SIN_EQUIVALENTE', 'Centro sin organización y evento sin equivalente'), ('EVENTO_SIN_EQUIVALENTE', 'Evento sin equivalente ENO'), ('PSEUDO_TOTAL_EXCLUIDO', 'Fila de total excluida por diseño'), ('SIN_ORGANIZACION', 'Consolidado sin organización')], max_length=45, verbose_name='Resolución')),
                ('calculado_en', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Calculado en')),
                ('evento', models.ForeignKey(blank=True, help_text='Vacío si la enfermedad legacy no tiene equivalente en el catálogo ENO.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conciliaciones_eno', to='vigilancia.eventoeno', verbose_name='Evento ENO')),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conciliaciones_eno', to='seguridad.organizacion', verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'Conciliación ENO',
                'verbose_name_plural': 'Conciliaciones ENO',
                'ordering': ('anio', 'semana', 'tipo', 'organizacion_id', 'legado_enfermedad_id'),
            },
        ),
        migrations.CreateModel(
            name='ConciliacionENOCentro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legado_establecimiento_id', models.BigIntegerField(db_index=True, verbose_name='ID establecimiento legacy')),
                ('legado_establecimiento_nombre', models.CharField(blank=True, max_length=200, verbose_name='Establecimiento legacy')),
                ('crudo_h', models.IntegerField(default=0, verbose_name='Casos hombres')),
                ('crudo_m', models.IntegerField(default=0, verbose_name='Casos mujeres')),
                ('sisv_h', models.IntegerField(blank=True, null=True, verbose_name='Casos SISV hombres')),
                ('sisv_m', models.IntegerField(blank=True, null=True, verbose_name='Casos SISV mujeres')),
                ('colision', models.BooleanField(default=False, verbose_name='Organización compartida')),
                ('conciliacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centros', to='conciliacion.conciliacioneno', verbose_name='Conciliación')),
            ],
            options={
                'verbose_name': 'Conciliación ENO por centro',
                'verbose_name_plural': 'Conciliaciones ENO por centro',
                'ordering': ('conciliacion__anio', 'conciliacion__semana', 'legado_establecimiento_id'),
            },
        ),
        migrations.AddIndex(
            model_name='conciliacioneno',
            index=models.Index(fields=['anio', 'semana', 'estado'], name='conciliacio_anio_c50894_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conciliacioneno',
            unique_together={('anio', 'semana', 'tipo', 'organizacion', 'legado_enfermedad_id')},
        ),
        migrations.AlterUniqueTogether(
            name='conciliacionenocentro',
            unique_together={('conciliacion', 'legado_establecimiento_id')},
        ),
    ]
