# Generated by Django 5.2.17 on 2026-09-29 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conciliacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conciliacionenocentro',
            name='legado_documento',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='Es único por centro+semana+tipo: identifica laHoja semanal que reportó el centro.', null=True, verbose_name='ID documento legacy'),
        ),
        migrations.AddField(
            model_name='conciliacionenocentro',
            name='transcrito_por',
            field=models.CharField(blank=True, help_text='INSTANCIA de HISTDOC: estación de trabajo, no cuenta verificada de persona. Vacío antes de agosto de 2019, cuando aún no se llevaba ese rastro.', max_length=30, verbose_name='Transcrito por'),
        ),
        migrations.AlterField(
            model_name='conciliacioneno',
            name='resolucion',
            field=models.CharField(choices=[('CONCILIADO', 'Conciliado'), ('CENTRO_SIN_ORG', 'Centro sin organización'), ('CENTRO_SIN_ORG_Y_EVENTO_SIN_EQUIVALENTE', 'Centro sin organización y evento sin equivalente'), ('EVENTO_SIN_EQUIVALENTE', 'Evento sin equivalente ENO'), ('PSEUDO_TOTAL_EXCLUIDO', 'Fila de total excluida por diseño'), ('SIN_FUENTE_EN_CRUDO', 'Sin fuente en el crudo')], max_length=45, verbose_name='Resolución'),
        ),
    ]
