# Generated by Django 5.2.17 on 2026-09-29 15:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conciliacion', '0003_conciliacion_neonatal'),
        ('seguridad', '0003_alter_perfil_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConciliacionMaterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.SmallIntegerField(db_index=True, verbose_name='Año')),
                ('semana', models.SmallIntegerField(db_index=True, verbose_name='Semana epidemiológica')),
                ('es_agregado_sin_org', models.BooleanField(default=False, help_text="El establecimiento legacy no resolvió a una organización y se sumó al agregado 'Legacy regional (histórico)'.", verbose_name='Pertenece al agregado regional')),
                ('cantidad_centros_legacy', models.PositiveIntegerField(default=1, verbose_name='Centros legacy')),
                ('legado', models.IntegerField(default=0, verbose_name='Muertes maternas en el registro de la oficina')),
                ('sisv', models.IntegerField(default=0, verbose_name='Muertes maternas marcadas en el certificado')),
                ('diferencia', models.IntegerField(default=0, verbose_name='Diferencia')),
                ('estado', models.CharField(choices=[('CUADRA', 'Cuadra'), ('DIFERENCIA', 'Diferencia'), ('SOLO_CRUDO', 'Solo en el registro de la oficina'), ('SOLO_SISV', 'Solo en SISV')], db_index=True, max_length=12, verbose_name='Estado')),
                ('resolucion', models.CharField(choices=[('CONCILIADO', 'Conciliado'), ('CENTRO_SIN_ORG', 'Centro sin organización')], max_length=20, verbose_name='Resolución')),
                ('calculado_en', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Calculado en')),
                ('organizacion', models.ForeignKey(help_text='A NULL cuando el establecimiento legacy no tiene organización propia; esos casos caen en el agregado regional, no se pierden.', on_delete=django.db.models.deletion.CASCADE, related_name='conciliaciones_materna', to='seguridad.organizacion', verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'Conciliación materna',
                'verbose_name_plural': 'Conciliaciones maternas',
                'ordering': ('anio', 'semana', 'organizacion_id'),
                'indexes': [models.Index(fields=['anio', 'estado'], name='conciliacio_anio_b9caeb_idx')],
                'unique_together': {('anio', 'semana', 'organizacion')},
            },
        ),
    ]
