# Generated by Django 5.2.17 on 2026-10-01 03:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seguridad', '0004_alter_perfil_rol'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Talonario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('NACIMIENTO', 'Nacimiento'), ('DEFUNCION', 'Defunción')], max_length=12, verbose_name='Tipo de certificado')),
                ('fecha_entrega', models.DateField(verbose_name='Fecha de entrega')),
                ('serie_desde', models.PositiveIntegerField(verbose_name='Serie desde')),
                ('serie_hasta', models.PositiveIntegerField(verbose_name='Serie hasta')),
                ('cantidad', models.PositiveIntegerField(default=0, editable=False, verbose_name='Cantidad entregada')),
                ('responsable_recibe', models.CharField(max_length=200, verbose_name='Responsable que recibe')),
                ('responsable_entrega', models.CharField(blank=True, default='', max_length=200, verbose_name='Responsable que entrega')),
                ('observaciones', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Registrado en')),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='talonarios', to='seguridad.organizacion', verbose_name='Centro médico')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Talonario despachado',
                'verbose_name_plural': 'Talonarios despachados',
                'ordering': ['-fecha_entrega', '-id'],
            },
        ),
        migrations.CreateModel(
            name='NovedadCertificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(verbose_name='Número del certificado')),
                ('estado', models.CharField(choices=[('DANADO', 'Dañado'), ('EN_TRANSITO', 'En tránsito'), ('DEVUELTO', 'Devuelto')], max_length=15, verbose_name='Estatus')),
                ('justificacion_numero', models.CharField(blank=True, default='', max_length=50, verbose_name='Nº de acta de justificación')),
                ('justificacion_fecha', models.DateField(blank=True, null=True, verbose_name='Fecha del acta de justificación')),
                ('transitado_nombres', models.CharField(blank=True, default='', max_length=150, verbose_name='Nombres (en tránsito)')),
                ('transitado_apellidos', models.CharField(blank=True, default='', max_length=150, verbose_name='Apellidos (en tránsito)')),
                ('fecha_salio_centro', models.DateField(blank=True, null=True, verbose_name='Fecha en que salió del centro')),
                ('observaciones', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('talonario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novedades', to='despacho.talonario', verbose_name='Talonario')),
            ],
            options={
                'verbose_name': 'Novedad de certificado',
                'verbose_name_plural': 'Novedades de certificados',
                'ordering': ['talonario', 'numero'],
            },
        ),
        migrations.AddConstraint(
            model_name='talonario',
            constraint=models.UniqueConstraint(fields=('centro', 'tipo', 'serie_desde', 'serie_hasta'), name='talonario_unico_por_serie'),
        ),
        migrations.AddConstraint(
            model_name='talonario',
            constraint=models.CheckConstraint(condition=models.Q(('serie_hasta__gte', models.F('serie_desde'))), name='talonario_serie_valida'),
        ),
        migrations.AddConstraint(
            model_name='novedadcertificado',
            constraint=models.UniqueConstraint(fields=('talonario', 'numero'), name='novedad_unica_por_certificado'),
        ),
    ]
