# Generated by Django 5.2.17 on 2026-08-11 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CIE10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripción')),
                ('capitulo', models.CharField(blank=True, max_length=300, verbose_name='Capítulo')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'CIE-10',
                'verbose_name_plural': 'CIE-10',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='CIE11',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=64, verbose_name='Código')),
                ('titulo', models.CharField(max_length=500, verbose_name='Título')),
                ('nivel', models.PositiveSmallIntegerField(choices=[(1, 'Capítulo'), (2, 'Bloque'), (3, 'Categoría'), (4, 'Subgrupo')], db_index=True, verbose_name='Nivel')),
                ('requiere_subgrupo', models.BooleanField(default=False, verbose_name='Requiere subgrupo obligatorio')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('capitulo', models.ForeignKey(blank=True, limit_choices_to={'nivel': 1}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalogos.cie11', verbose_name='Capítulo')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='catalogos.cie11', verbose_name='Nodo padre')),
            ],
            options={
                'verbose_name': 'CIE-11',
                'verbose_name_plural': 'CIE-11',
                'ordering': ['nivel', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='MapeoCIE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('EXA', 'Exacto'), ('PAR', 'Parcial'), ('INE', 'Inexacto')], default='EXA', max_length=3, verbose_name='Tipo de equivalencia')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('cie10', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapeos', to='catalogos.cie10')),
                ('cie11', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapeos', to='catalogos.cie11')),
            ],
            options={
                'verbose_name': 'Equivalencia CIE-10 <-> CIE-11',
                'verbose_name_plural': 'Equivalencias CIE-10 <-> CIE-11',
            },
        ),
        migrations.AddConstraint(
            model_name='cie11',
            constraint=models.UniqueConstraint(fields=('codigo', 'padre'), name='uq_cie11_codigo_padre'),
        ),
        migrations.AddConstraint(
            model_name='mapeocie',
            constraint=models.UniqueConstraint(fields=('cie10', 'cie11'), name='uq_mapeo_cie10_cie11'),
        ),
    ]
