# Generated by Django 5.2.17 on 2026-09-16 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cie10',
            name='origen',
            field=models.CharField(choices=[('OMS', 'OMS/OPS'), ('LEGACY', 'Legacy (SISMAI)')], default='OMS', max_length=10, verbose_name='Origen'),
        ),
    ]
