-- ============================================================================
--  schema_t_eventos_04082026.sql
--  ESTRUCTURA REAL de las 83 tablas TEMP.T_* del paquete del 04/08/2026
--  (routlar1_482026_1526.ZIP), extraida con DBMS_METADATA del esquema
--  IMPORT29 del espejo Oracle local (legancy/BDSISMAI.DMP).
--
--  Cierra el hueco de legancy/analisis/schema_routlar1.sql, que estaba
--  truncado. Ver PENDIENTES.md 17.13.
--  83 CREATE TABLE + 86 CREATE INDEX = los 83 "Table created" y los 86
--  "Index created" de repllar1.log.
-- ============================================================================

-- Para aplicar en un servidor de prueba: crear antes el usuario TEMP
-- y reemplazar el esquema destino si no se llama TEMP.
;

-- ===== T_ACCILABO =====

  CREATE TABLE "TEMP"."T_ACCILABO"
   (	"ID" NUMBER NOT NULL ENABLE,
	"ACCIDENTE" NUMBER,
	"HFICHAS_EPIDEMIOLOGICAS" NUMBER NOT NULL ENABLE,
	"FECHA" DATE,
	"HORA" VARCHAR2(20),
	"HCENTROASISTENCIAL" NUMBER,
	"TRATAMIENTO" VARCHAR2(1),
	"ESQUEMA" VARCHAR2(1),
	"FECHATRA" DATE,
	"HORATRATAMIENTO" VARCHAR2(20),
	"FUENTE" VARCHAR2(1),
	"DESCONOCE" NUMBER,
	"FUENTEDESCONOCE" NUMBER,
	"SEROLOGIA" VARCHAR2(1),
	"RESULTADOSERO" VARCHAR2(30),
	"FECHARESULTADOSERO" DATE,
	"HEXPOSICION" NUMBER,
	"HOBJETO" NUMBER,
	"HLIQUIDO" NUMBER,
	"HSITUACION" NUMBER,
	"ABUSOSEXUAL" NUMBER,
	"HLOCALIDADABUSO" NUMBER,
	"FECHAABUSO" DATE,
	"HORAABUSO" VARCHAR2(20)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_ACCTRANS =====

  CREATE TABLE "TEMP"."T_ACCTRANS"
   (	"ID" NUMBER NOT NULL ENABLE,
	"HFICHA" NUMBER NOT NULL ENABLE,
	"HTIPO_ACCIDENTE" NUMBER NOT NULL ENABLE,
	"HTIPO_VEHICULO" NUMBER NOT NULL ENABLE,
	"HCONDICION" NUMBER NOT NULL ENABLE,
	"HSITIO_ACCIDENTE" NUMBER NOT NULL ENABLE,
	"HDIAGNOSTICO" NUMBER NOT NULL ENABLE,
	"HUBICACION" NUMBER NOT NULL ENABLE,
	"HSITIO_AUTO" NUMBER,
	"HCIE10" NUMBER,
	"CAUSA" NUMBER
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_ALABCARD =====

  CREATE TABLE "TEMP"."T_ALABCARD"
   (	"ID" NUMBER NOT NULL ENABLE,
	"HFICHAS_EPIDEMIOLOGICAS" NUMBER NOT NULL ENABLE,
	"HRELACION_PROG_ANALISIS" NUMBER NOT NULL ENABLE,
	"HSEG_EVOL_PACIENTE" NUMBER NOT NULL ENABLE,
	"USUARIO" VARCHAR2(10),
	"FECHAOPERACION" DATE,
	"FECHA_ANALISIS" DATE,
	"RESULTADO" VARCHAR2(50)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_ANALABOR =====

  CREATE TABLE "TEMP"."T_ANALABOR"
   (	"ID" FLOAT(126) NOT NULL ENABLE,
	"HFICHAS_EPIDEMIOLOGICAS" FLOAT(126),
	"HRELACION_PROG_ANALISIS" FLOAT(126),
	"HSEG_EVOL_PACIENTE" FLOAT(126),
	"USUARIO" VARCHAR2(10),
	"FECHAOPERACION" DATE,
	"FECHA_ANALISIS" DATE,
	"RESULTADO" VARCHAR2(50),
	"HPROG_M_CH_E" NUMBER
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_ANTEFACT =====

  CREATE TABLE "TEMP"."T_ANTEFACT"
   (	"ID" FLOAT(126) NOT NULL ENABLE,
	"HFICHAS_EPIDEMIOLOGICAS" FLOAT(126),
	"HRELACION_PROG_ANTECED" FLOAT(126) NOT NULL ENABLE,
	"USUARIO" VARCHAR2(10),
	"FECHAOPERACION" DATE,
	"HPROG_M_CH_E" NUMBER
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_AUDITORIA =====

  CREATE TABLE "TEMP"."T_AUDITORIA"
   (	"ID" NUMBER NOT NULL ENABLE,
	"NOMBREFORMA" VARCHAR2(60) NOT NULL ENABLE,
	"NOMBRETABLA" VARCHAR2(30) NOT NULL ENABLE,
	"EVENTO" NUMBER NOT NULL ENABLE,
	"NOMBREREGISTRO" VARCHAR2(200) NOT NULL ENABLE,
	"IDREGISTRO" NUMBER NOT NULL ENABLE,
	"PC" VARCHAR2(20),
	"HUSUARIO" NUMBER,
	"FECHA_OPE" DATE,
	"STATUS" NUMBER
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_BIOPSEG =====

  CREATE TABLE "TEMP"."T_BIOPSEG"
   (	"ID" FLOAT(126) NOT NULL ENABLE,
	"DESCRIPCION" VARCHAR2(2000)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_BIOPSIAT =====

  CREATE TABLE "TEMP"."T_BIOPSIAT"
   (	"ID" FLOAT(126) NOT NULL ENABLE,
	"ASPECTOCLINICO" FLOAT(126),
	"BIOPSIAANTERIOR" NUMBER(*,0),
	"CENEOPLASICAS" NUMBER(*,0),
	"CEREACTIVAS" NUMBER(*,0),
	"CGNEOPLASICAS" NUMBER(*,0),
	"CGREACTIVAS" NUMBER(*,0),
	"CITANORMAL" FLOAT(126),
	"CITOLOGIAANT" NUMBER(*,0),
	"CITOLOGIANEOPLASIA" NUMBER(*,0),
	"CODIGOMUESTRASAS" VARCHAR2(8),
	"CRINFECCIOSOS" NUMBER(*,0),
	"CRINFLAMATORIOS" NUMBER(*,0),
	"DIRECCIONHABITUAL" VARCHAR2(100),
	"EMBARAZADA" NUMBER(*,0),
	"FECHACRIOCIRUGIA" DATE,
	"FECHACONIZACION" DATE,
	"FECHADOC" DATE NOT NULL ENABLE,
	"FECHAHISTRADICAL" DATE,
	"FECHAHISTTOTAL" DATE,
	"FECHALECTURA" DATE,
	"FECHAMUESTRA" DATE,
	"FECHARADIOTERAPIA" DATE,
	"FECHARESULTADO" DATE,
	"FECHAULTREGLA" DATE,
	"HLABORATORIO" FLOAT(126),
	"HLOCALIZACION" FLOAT(126),
	"HMEDICO" FLOAT(126),
	"HPACIENTE" FLOAT(126) NOT NULL ENABLE,
	"HPATOLOGO" FLOAT(126),
	"HUBICACION" FLOAT(126),
	"LOCALIZACION" VARCHAR2(254),
	"MESBIOPSIA" DATE,
	"MESCITOLOGIA" DATE,
	"MUESTRACITOLOGICA" NUMBER(*,0),
	"NROPARTO" FLOAT(126),
	"NROABORTO" FLOAT(126),
	"NROLAMINA" VARCHAR2(20),
	"NUMERO" FLOAT(126) NOT NULL ENABLE,
	"OBSERVACIONES" VARCHAR2(600),
	"RESULTADOASOCIADO" FLOAT(126),
	"HRESULTADOB" FLOAT(126),
	"HRESULTADOC" FLOAT(126),
	"TELEFONOH" VARCHAR2(12),
	"TELEFONOL" VARCHAR2(12),
	"TIPOEXAMEN" FLOAT(126),
	"TIPOMUESTRA1" NUMBER(*,0),
	"TIPOMUESTRA2" NUMBER(*,0),
	"TRATAMIENTOPREVIO" NUMBER(*,0),
	"VALORLECTURA" FLOAT(126),
	"VPH" NUMBER(*,0),
	"USUARIO_AMB" VARCHAR2(10),
	"USUARIO_LAB" VARCHAR2(10),
	"HCENTROMUESTRA" FLOAT(126) NOT NULL ENABLE,
	"OBSERVACIONESMACRO" VARCHAR2(4000),
	"MUESTRAUTERO" VARCHAR2(50)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_CASOSMM =====

  CREATE TABLE "TEMP"."T_CASOSMM"
   (	"ID" NUMBER NOT NULL ENABLE,
	"HDOCUMENTO" NUMBER NOT NULL ENABLE,
	"NUM_PARTOS" NUMBER,
	"HIJOS_NACVIVOS" NUMBER,
	"HIJOS_NACMUERTOS" NUMBER,
	"HIJOS_NACABORTOS" NUMBER,
	"FECHAOPERACION" DATE,
	"USUARIO" VARCHAR2(25)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_CASOSMMI =====

  CREATE TABLE "TEMP"."T_CASOSMMI"
   (	"ID" NUMBER NOT NULL ENABLE,
	"HDOCUMENTO" NUMBER NOT NULL ENABLE,
	"NOMBRE" VARCHAR2(25),
	"APELLIDO" VARCHAR2(25),
	"EDAD" NUMBER,
	"UNIDAD_EDAD" VARCHAR2(1),
	"HSEXO" FLOAT(126),
	"HETNIA" NUMBER,
	"FECHAOCURRENCIA" DATE,
	"HRESIDENCIA" NUMBER,
	"FECHAOPERACION" DATE,
	"USUARIO" VARCHAR2(25),
	"HOCUPACION" NUMBER,
	"HRESIDENCIA_PAIS" NUMBER,
	"NACIONALIDAD" VARCHAR2(1),
	"CEDULA" VARCHAR2(12),
	"NUMEROMSDS" VARCHAR2(10)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_CAUMMEDI =====

  CREATE TABLE "TEMP"."T_CAUMMEDI"
   (	"ID" FLOAT(126) NOT NULL ENABLE,
	"HCERTIFICADO" NUMBER NOT NULL ENABLE,
	"HCIE10" NUMBER,
	"ORDENLISTA" VARCHAR2(1),
	"CAUSA1" VARCHAR2(120),
	"CAUSA2" VARCHAR2(120),
	"CAUSA3" VARCHAR2(120),
	"INTERVALO" VARCHAR2(30),
	"FECHAOPERACION" DATE,
	"USUARIO" VARCHAR2(10)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_CERTMORT =====

  CREATE TABLE "TEMP"."T_CERTMORT"
   (	"ID" FLOAT(126),
	"HESTABLECIMIENTO" NUMBER NOT NULL ENABLE,
	"NUMEROPARTIDA" VARCHAR2(10),
	"NUMEROMSDS" VARCHAR2(10),
	"CERTIFICADO" VARCHAR2(10),
	"ANNOCERTIFICADO" NUMBER,
	"MFETAL" NUMBER,
	"NOMBRE" VARCHAR2(100),
	"APELLIDO" VARCHAR2(100),
	"NACIONALIDAD" NUMBER,
	"CEDULA" VARCHAR2(15),
	"SEXO" NUMBER,
	"FECHA_M" DATE,
	"FECHA_N" DATE,
	"EDAD" NUMBER,
	"TIPOEDAD" VARCHAR2(1),
	"HESTADOCIVIL" NUMBER,
	"ANNOCURSADO" NUMBER,
	"ANNOTERMINADO" NUMBER,
	"HULTIMOGRADO" NUMBER,
	"HPROFESION" NUMBER,
	"HOCUPACION" NUMBER,
	"HPAIS" NUMBER,
	"HSITIO_M" NUMBER,
	"NOMBRECLINICA" VARCHAR2(100),
	"HLOCAOCURRENCIA" NUMBER,
	"DIRECOCURRENCIA" VARCHAR2(250),
	"HLOCARESIDENCIA" NUMBER,
	"DIRECRESIDENCIA" VARCHAR2(200),
	"HPRESENCIAEMBARAZO" NUMBER,
	"HCAUSABASICA" NUMBER,
	"OTROSESTADOS" VARCHAR2(400),
	"AUTOPSIA" NUMBER,
	"EXAMENCUERPO" NUMBER,
	"EXAMENLAB" NUMBER,
	"INTERROGATORIO" NUMBER,
	"HISTORIACLINICA" NUMBER,
	"NUMERODIAGNOSTICO" VARCHAR2(10),
	"HMEDICOFIRMANTE" NUMBER,
	"OTROMEDFIRMANTE" VARCHAR2(100),
	"ASISTENCIAMEDICA" NUMBER,
	"HMEDICO" NUMBER,
	"FIRMAMEDICO" NUMBER,
	"DIRECSERVICIO_M" VARCHAR2(200),
	"DESCERNOMEDICA" VARCHAR2(250),
	"HDESTINOCUERPO" NUMBER,
	"NUMEROPERMISO" VARCHAR2(10),
	"HREGIONPERMISO" NUMBER,
	"LUGARPERMISO" VARCHAR2(200),
	"FECHAPERMISO" DATE,
	"HREGIONEXPE" NUMBER,
	"LUGAREXPEDICION" VARCHAR2(200),
	"FECHAEXPE" DATE,
	"FIRMAAUTORIDAD" NUMBER,
	"SELLO" NUMBER,
	"STATUS" NUMBER,
	"FECHAOPERACION" DATE,
	"LOGIN" VARCHAR2(10),
	"HMADRE" NUMBER,
	"CONSECUTIVO" VARCHAR2(20),
	"EDAD2" NUMBER,
	"TIPOEDAD2" VARCHAR2(1),
	"TRANSRESI" NUMBER,
	"HETNIA" NUMBER,
	"SABELEER" VARCHAR2(1),
	"HIJOSNAC_V" NUMBER,
	"HIJOSNAC_AV" NUMBER,
	"HIJOSNAC_M" NUMBER,
	"HIJOSNAC_MF" NUMBER,
	"TOMO" VARCHAR2(50),
	"FOLIO" VARCHAR2(50),
	"LIBRO" VARCHAR2(50),
	"ACTA" VARCHAR2(50),
	"NACMADREFALLECIDO" NUMBER,
	"CIMADREFALLECIDO" VARCHAR2(15),
	"NOMMADREFALLECIDO" VARCHAR2(50),
	"NACPADREFALLECIDO" NUMBER,
	"CIPADREFALLECIDO" VARCHAR2(15),
	"NOMPADREFALLECIDO" VARCHAR2(50),
	"NACREGISTRADOR" NUMBER,
	"CIREGISTRADOR" VARCHAR2(10),
	"NOMREGISTRADOR" VARCHAR2(50),
	"TOMOPARTIDANAC" VARCHAR2(50),
	"FOLIOPARTIDANAC" VARCHAR2(50),
	"LIBROPARTIDANAC" VARCHAR2(50),
	"ACTAPARTIDANAC" VARCHAR2(50),
	"HORAMUERTE" VARCHAR2(20),
	"HESTADO" NUMBER,
	"HLOCARESIDENCIAFP" NUMBER,
	"HESTABLECIMIENTO_OCUR" NUMBER,
	"ESPECIAL" NUMBER,
	"OTRODIAGNOSTICO" NUMBER,
	"OTRODIAGNOSTICOCERT" VARCHAR2(50),
	"FECHAELABORACION" DATE,
	"NUMEROAUTOPSIA" VARCHAR2(20),
	"OBSERVACION" VARCHAR2(500)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_CERTNACI =====

  CREATE TABLE "TEMP"."T_CERTNACI"
   (	"ID" FLOAT(126),
	"NROPLANILLA" VARCHAR2(20),
	"FECHACERTIFICADO" DATE,
	"HTIPODEREGISTRO" FLOAT(126),
	"CEDULA" VARCHAR2(10),
	"CODIGOSAS" VARCHAR2(10),
	"NOMBRES" VARCHAR2(100),
	"OBSERVACIONES" VARCHAR2(200),
	"FECHAOPERACION" DATE,
	"USUARIO" VARCHAR2(15),
	"HLOCALIDADOC" FLOAT(126),
	"HESTABLECIMIENTO" FLOAT(126) NOT NULL ENABLE,
	"NOMBREDIRECTOR" VARCHAR2(100),
	"STATUS" NUMBER,
	"CONSECUTIVO" VARCHAR2(20),
	"ANO_CERTIF" NUMBER,
	"ACTADENACIMENTO" CHAR(50),
	"TOMO" CHAR(50),
	"FOLIO" CHAR(50),
	"LIBRO" CHAR(50),
	"TESTIGO1" CHAR(40),
	"TESTIGOCI1" CHAR(10),
	"TESTIGOEDAD1" NUMBER,
	"TESTIGO2" CHAR(40),
	"TESTIGOCI2" CHAR(10),
	"TESTIGOEDAD2" NUMBER,
	"JEFECIVIL" CHAR(40),
	"JEFECIVILCI" CHAR(10),
	"FECHAREGCIVIL" DATE,
	"ESPECIAL" NUMBER
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_COMAGUDA =====

  CREATE TABLE "TEMP"."T_COMAGUDA"
   (	"ID" NUMBER NOT NULL ENABLE,
	"HFICHAS_EPIDEMIOLOGICAS" NUMBER,
	"HRELACION_PROG_COMPLICA" NUMBER,
	"USUARIO" VARCHAR2(10),
	"FECHAOPERACION" DATE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_COMCRONI =====

  CREATE TABLE "TEMP"."T_COMCRONI"
   (	"ID" NUMBER NOT NULL ENABLE,
	"HFICHAS_EPIDEMIOLOGICAS" NUMBER,
	"HRELACION_PROG_COMPLICA" NUMBER,
	"USUARIO" VARCHAR2(10),
	"FECHAOPERACION" DATE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_COMDISCA =====

  CREATE TABLE "TEMP"."T_COMDISCA"
   (	"ID" NUMBER NOT NULL ENABLE,
	"HFICHAS_EPIDEMIOLOGICAS" NUMBER,
	"HRELACION_PROG_COMPLICA" NUMBER,
	"USUARIO" VARCHAR2(10),
	"FECHAOPERACION" DATE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_COMPCARD =====

  CREATE TABLE "TEMP"."T_COMPCARD"
   (	"ID" NUMBER NOT NULL ENABLE,
	"HFICHAS_EPIDEMIOLOGICAS" NUMBER,
	"HRELACION_PROG_COMPLICA" NUMBER,
	"TIPO" VARCHAR2(1),
	"USUARIO" VARCHAR2(10),
	"FECHAOPERACION" DATE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_COMPLICA =====

  CREATE TABLE "TEMP"."T_COMPLICA"
   (	"ID" NUMBER NOT NULL ENABLE,
	"HFICHAS_EPIDEMIOLOGICAS" NUMBER,
	"HRELACION_PROG_COMPLICA" NUMBER,
	"HSEG_EVOL_PACIENTE" NUMBER,
	"USUARIO" VARCHAR2(10),
	"FECHAOPERACION" DATE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_COMQUIR =====

  CREATE TABLE "TEMP"."T_COMQUIR"
   (	"ID" NUMBER NOT NULL ENABLE,
	"HREGISTROCIRUGIA" NUMBER NOT NULL ENABLE,
	"HCOMPLICACION" NUMBER NOT NULL ENABLE,
	"HTIPOCOMPLICACION" NUMBER,
	"USUARIO" VARCHAR2(10),
	"FECHAOPERACION" DATE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_COMSEGIM =====

  CREATE TABLE "TEMP"."T_COMSEGIM"
   (	"ID" NUMBER NOT NULL ENABLE,
	"HFICHAS_EPIDEMIOLOGICAS" NUMBER,
	"HRELACION_PROG_COMPLICA" NUMBER,
	"HSEG_EVOL_PACIENTE" NUMBER,
	"USUARIO" VARCHAR2(10),
	"FECHAOPERACION" DATE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_DIAGASOC =====

  CREATE TABLE "TEMP"."T_DIAGASOC"
   (	"ID" FLOAT(126) NOT NULL ENABLE,
	"HFICHAS_EPIDEMIOLOGICAS" FLOAT(126),
	"HCIE10" NUMBER(10,0),
	"USUARIO" VARCHAR2(10),
	"FECHAOPERACION" DATE,
	"HPROG_M_CH_E" NUMBER
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_DOCUDENG =====

  CREATE TABLE "TEMP"."T_DOCUDENG"
   (	"ID" FLOAT(126) NOT NULL ENABLE,
	"HDOCUMENTO" FLOAT(126) NOT NULL ENABLE,
	"C_FIEBRE" NUMBER,
	"C_HEMORRAGICO" NUMBER,
	"C_HOSPITALIZADO" NUMBER,
	"C_MUESTRA" NUMBER,
	"C_POSITIVO" NUMBER,
	"C_NEGATIVO" NUMBER,
	"C_PENDIENTE" NUMBER,
	"C_EPIDEMIOLOGICO" NUMBER,
	"C_LABORATORIO" NUMBER,
	"NRO_SEMANA" NUMBER,
	"CASOS_SEMANA" NUMBER,
	"HTIPODENGUE" NUMBER,
	"FECHAOPERACION" DATE,
	"USUARIO" VARCHAR2(10),
	"TOTALDENGUE" NUMBER
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_DOCUMENT =====

  CREATE TABLE "TEMP"."T_DOCUMENT"
   (	"ID" FLOAT(126) NOT NULL ENABLE,
	"FECHA" DATE,
	"STATUS" FLOAT(126),
	"TIPO" FLOAT(126) NOT NULL ENABLE,
	"HORIGEN" FLOAT(126) NOT NULL ENABLE,
	"OBSERVACIONES" VARCHAR2(500),
	"PERIODO" FLOAT(126),
	"HCATEGORIA" FLOAT(126),
	"ANNO" FLOAT(126),
	"NUMERO" VARCHAR2(20),
	"USUARIO" VARCHAR2(15),
	"FECHAOPERACION" DATE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_DOCUSOSP =====

  CREATE TABLE "TEMP"."T_DOCUSOSP"
   (	"ID" FLOAT(126) NOT NULL ENABLE,
	"HDOCUMENTO" FLOAT(126) NOT NULL ENABLE,
	"C_ESTUDIO" NUMBER,
	"C_DESCARTADO" NUMBER,
	"C_CONFIRMADO" NUMBER,
	"C_COMPARTIDO" NUMBER,
	"C_NOTIFICADO" NUMBER
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_ESTABLE =====

  CREATE TABLE "TEMP"."T_ESTABLE"
   (	"ID" FLOAT(126) NOT NULL ENABLE,
	"CODIGO" VARCHAR2(20) NOT NULL ENABLE,
	"NOMBRE" VARCHAR2(150) NOT NULL ENABLE,
	"PADRE" FLOAT(126),
	"HTIPO" FLOAT(126),
	"DIRECCION" VARCHAR2(250),
	"HLOCALIDAD" FLOAT(126),
	"TELEFONO" VARCHAR2(50),
	"STATUS" CHAR(1),
	"FECHAOPERACION" DATE,
	"USUARIO" CHAR(10),
	"DOMICILIADO" CHAR(1),
	"RIF" VARCHAR2(20),
	"TIPOESTABLEC" FLOAT(126),
	"CUENTADANTE" FLOAT(126),
	"HNIVEL" FLOAT(126),
	"X_UTM" NUMBER(24,6),
	"Y_UTM" NUMBER(24,6),
	"ALTITUD" NUMBER(10,2),
	"FUNCIONAMIENTO" VARCHAR2(1),
	"HDEPENDENCIA_ADM" NUMBER
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_EVENTOS =====

  CREATE TABLE "TEMP"."T_EVENTOS"
   (	"TABLA" VARCHAR2(100) NOT NULL ENABLE,
	"EVENTO" CHAR(1) NOT NULL ENABLE,
	"FECHA" DATE,
	"ID" FLOAT(126) NOT NULL ENABLE,
	"STATUS" NUMBER(1,0),
	"AMS" VARCHAR2(12)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_FDOLORTO =====

  CREATE TABLE "TEMP"."T_FDOLORTO"
   (	"ID" NUMBER NOT NULL ENABLE,
	"HFICHA_PROGRAMA" NUMBER NOT NULL ENABLE,
	"HFICHADELDOLOR" NUMBER NOT NULL ENABLE,
	"SI" NUMBER,
	"NO" NUMBER
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_FICHAACC =====

  CREATE TABLE "TEMP"."T_FICHAACC"
   (	"ID" NUMBER NOT NULL ENABLE,
	"HPACIENTE" NUMBER NOT NULL ENABLE,
	"NUMERO" VARCHAR2(15) NOT NULL ENABLE,
	"FECHA_OC" DATE,
	"HORA_OC" VARCHAR2(20),
	"HLOCALIDAD_OC" NUMBER NOT NULL ENABLE,
	"SITIO_OC" VARCHAR2(150),
	"HESTABLECIMIENTO" NUMBER NOT NULL ENABLE,
	"FALLECIO" NUMBER,
	"HORA_MUERTE" VARCHAR2(20),
	"HSITIO_MUERTE" NUMBER,
	"INFLUENCIA_ALCOHOL" NUMBER
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_FICHASEP =====

  CREATE TABLE "TEMP"."T_FICHASEP"
   (	"ID" FLOAT(126) NOT NULL ENABLE,
	"HPACIENTE" FLOAT(126) NOT NULL ENABLE,
	"FECHAREGISTRO" DATE,
	"HCENTROASISTENCIAL" FLOAT(126),
	"HLOCALIDAD_FICHA" NUMBER(10,0),
	"NRO_CASO" VARCHAR2(20),
	"HPROGRAMA" FLOAT(126),
	"USUARIO" VARCHAR2(10),
	"FECHAOPERACION" DATE,
	"ANO_FECHA_REG" NUMBER(4,0),
	"DIRECCIONHABITUAL" VARCHAR2(254),
	"HUBICACION" NUMBER,
	"LOCALIZACION" VARCHAR2(254),
	"HLOCALIZACION" NUMBER
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_HECHOSVI =====

  CREATE TABLE "TEMP"."T_HECHOSVI"
   (	"ID" NUMBER NOT NULL ENABLE,
	"HFICHA" NUMBER NOT NULL ENABLE,
	"HTIPO_HECHO" NUMBER NOT NULL ENABLE,
	"HSITIO_OCURRENCIA" NUMBER NOT NULL ENABLE,
	"HEFECTUO_HECHO" NUMBER NOT NULL ENABLE,
	"HDIAGNOSTICO" NUMBER,
	"HUBIC_DIAGNOSTICO" NUMBER,
	"HCIE10" NUMBER
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_INTQUIR =====

  CREATE TABLE "TEMP"."T_INTQUIR"
   (	"ID" NUMBER NOT NULL ENABLE,
	"HREGISTROCIRUGIA" NUMBER NOT NULL ENABLE,
	"HDIAGNOSTICO" NUMBER,
	"HINTERVENCION" NUMBER NOT NULL ENABLE,
	"HANATOMIA" NUMBER,
	"OBSERVACION" VARCHAR2(1000),
	"USUARIO" VARCHAR2(10),
	"FECHAOPERACION" DATE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_LUGARVIS =====

  CREATE TABLE "TEMP"."T_LUGARVIS"
   (	"ID" FLOAT(126) NOT NULL ENABLE,
	"HPROG_M_CH_E" FLOAT(126) NOT NULL ENABLE,
	"FECHA" DATE,
	"LUGAR" VARCHAR2(200),
	"TIEMPO_PERM" NUMBER(3,0),
	"UNID_TIEMPERM" VARCHAR2(10),
	"USUARIO" VARCHAR2(10),
	"FECHAOPERACION" DATE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_MADRNACI =====

  CREATE TABLE "TEMP"."T_MADRNACI"
   (	"ID" FLOAT(126),
	"HCERTIFICADO" FLOAT(126) NOT NULL ENABLE,
	"CEDULA" VARCHAR2(10),
	"NOMBRES" VARCHAR2(100),
	"APELLIDOS" VARCHAR2(100),
	"PASAPORTE" VARCHAR2(20),
	"DIRECCION" VARCHAR2(100),
	"HRESIDENCIA" FLOAT(126),
	"HISTORIACLINICA" VARCHAR2(20),
	"PHISTORIACLINICA" VARCHAR2(20),
	"FECHANACIMIENTO" DATE,
	"EDADM" FLOAT(126),
	"EDADP" FLOAT(126),
	"ESTADOCIVIL" FLOAT(126),
	"ANNOSMATRIMONIO" FLOAT(126),
	"NACVIVOS" FLOAT(126),
	"NACIONM" FLOAT(126),
	"NACIONP" FLOAT(126),
	"HENTIDAM" FLOAT(126),
	"HENTIDAP" FLOAT(126),
	"HPAISM" FLOAT(126),
	"HPAISP" FLOAT(126),
	"ACTUALVIVOS" FLOAT(126),
	"LEERESCRIBIR" FLOAT(126),
	"NACVIVOSFALLEC" FLOAT(126),
	"MUERTESFETALES" FLOAT(126),
	"HULTIMOGRADO" FLOAT(126),
	"PROFESION" FLOAT(126),
	"CONTROLPRENATAL" FLOAT(126),
	"TELEFONOM" VARCHAR2(20),
	"PTELEFONO" VARCHAR2(20),
	"OCUPACION" FLOAT(126),
	"PCEDULA" VARCHAR2(10),
	"PNOMBRES" VARCHAR2(100),
	"PPASAPORTE" VARCHAR2(20),
	"PDIRECCION" VARCHAR2(100),
	"HPRESIDENCIA" FLOAT(126),
	"PFECHANACIMIENTO" DATE,
	"PESTADOCIVIL" FLOAT(126),
	"PLEERESCRIBIR" FLOAT(126),
	"HPULTIMOGRADO" FLOAT(126),
	"PPROFESION" FLOAT(126),
	"OBSERVACION" VARCHAR2(100),
	"POCUPACION" FLOAT(126),
	"FECHAOPERACION" DATE,
	"USUARIO" VARCHAR2(15),
	"NACIONALIDAP" FLOAT(126),
	"NACIONALIDAM" FLOAT(126),
	"UNIONMAT" NUMBER,
	"NROCONSULTASPRE" NUMBER,
	"HETNIAM" NUMBER,
	"HETNIAP" NUMBER,
	"HABLAETNIAM" NUMBER,
	"HABLAETNIAP" NUMBER,
	"ULTIMOGRADOM" NUMBER,
	"ULTIMOGRADOP" NUMBER,
	"RESIDENCIAM" NUMBER(1,0),
	"HRESIDENCIA_PAISM" NUMBER,
	"RESIDENCIAP" NUMBER(1,0),
	"HRESIDENCIA_PAISP" NUMBER
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_MBASED =====

  CREATE TABLE "TEMP"."T_MBASED"
   (	"ID" FLOAT(126) NOT NULL ENABLE,
	"SID" VARCHAR2(10) NOT NULL ENABLE,
	"FECHA" DATE NOT NULL ENABLE,
	"TEXTO_FECHA" VARCHAR2(20) NOT NULL ENABLE,
	"NOMBRE_TABLESPACE" VARCHAR2(50) NOT NULL ENABLE,
	"TS_SIZE_MB" NUMBER(11,2) NOT NULL ENABLE,
	"TS_USADO_MB" NUMBER(11,2) NOT NULL ENABLE,
	"TS_USADO_PC" NUMBER(11,2) NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_MCAUMORB =====

  CREATE TABLE "TEMP"."T_MCAUMORB"
   (	"ID" FLOAT(126),
	"HCERTIFICADO" NUMBER NOT NULL ENABLE,
	"HCIE10" NUMBER NOT NULL ENABLE,
	"LOGIN" VARCHAR2(10),
	"FECHAOPERACION" DATE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_MCAUSMRE =====

  CREATE TABLE "TEMP"."T_MCAUSMRE"
   (	"ID" FLOAT(126),
	"HCERTIFICADO" NUMBER NOT NULL ENABLE,
	"HCIE10" NUMBER NOT NULL ENABLE,
	"INTERVALO" VARCHAR2(30),
	"DESENFERMEDAD" VARCHAR2(200),
	"ORDENLISTA" VARCHAR2(1),
	"LOGIN" VARCHAR2(10),
	"FECHAOPERACION" DATE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_MHOJAREP =====

  CREATE TABLE "TEMP"."T_MHOJAREP"
   (	"ID" FLOAT(126) NOT NULL ENABLE,
	"HCERTIFICADO" NUMBER NOT NULL ENABLE,
	"HESTABLECIMIENTO" NUMBER NOT NULL ENABLE,
	"REPARAPOR" NUMBER,
	"ATRAVESDE" NUMBER,
	"HISTORIACLINICA" VARCHAR2(10),
	"FECHAREPARA" DATE,
	"OTROSMEDIOS" VARCHAR2(100),
	"NOMBRECLINICO" VARCHAR2(100),
	"NACMEDICO" NUMBER,
	"CEDULACLINICO" VARCHAR2(15),
	"NOMBREEPIDEM" VARCHAR2(100),
	"NACEPIDEM" NUMBER,
	"CEDULAEPIDEM" VARCHAR2(15),
	"OBSERVACION" VARCHAR2(200),
	"FECHAOPERACION" DATE,
	"USUARIO" VARCHAR2(10)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_MORTANUL =====

  CREATE TABLE "TEMP"."T_MORTANUL"
   (	"ID" NUMBER NOT NULL ENABLE,
	"HESTABLECIMIENTO" NUMBER NOT NULL ENABLE,
	"HCAUSAANULADO" NUMBER NOT NULL ENABLE,
	"NROPLANILLA" VARCHAR2(20) NOT NULL ENABLE,
	"CONSECUTIVO" VARCHAR2(20) NOT NULL ENABLE,
	"ANO_CERTIF" NUMBER,
	"FECHA_ANULADO" DATE,
	"CAUSA_ANULADO" VARCHAR2(200) NOT NULL ENABLE,
	"USUARIO" VARCHAR2(10),
	"FECHA_OPERACION" DATE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_MORTCAUS =====

  CREATE TABLE "TEMP"."T_MORTCAUS"
   (	"ID" FLOAT(126),
	"HCERTIFICADO" NUMBER NOT NULL ENABLE,
	"HCIE10" NUMBER NOT NULL ENABLE,
	"INTERVALO" VARCHAR2(30),
	"DESENFERMEDAD" VARCHAR2(200),
	"ORDENLISTA" VARCHAR2(1),
	"LOGIN" VARCHAR2(10),
	"FECHAOPERACION" DATE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_MORTFETA =====

  CREATE TABLE "TEMP"."T_MORTFETA"
   (	"ID" NUMBER,
	"HCERTIFICADO" NUMBER NOT NULL ENABLE,
	"HMADRE" NUMBER,
	"HDURACIONEMBA" NUMBER,
	"HNACTIPOEMBA" NUMBER,
	"HFORMAPARTO" NUMBER,
	"HM_RELAPARTO" NUMBER,
	"PESOFETO" NUMBER,
	"IGNORADOPESO" NUMBER,
	"FECHAOPERACION" DATE,
	"LOGIN" VARCHAR2(10),
	"HASISTENTEPARTO" NUMBER,
	"OTROASISTPARTO" VARCHAR2(50)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_MORTMADR =====

  CREATE TABLE "TEMP"."T_MORTMADR"
   (	"ID" FLOAT(126),
	"NOMBRE" VARCHAR2(100),
	"APELLIDO" VARCHAR2(100),
	"EDAD" NUMBER,
	"NACIONALIDAD" NUMBER,
	"CEDULA" VARCHAR2(15),
	"HPROFESION" NUMBER,
	"HOCUPACION" NUMBER,
	"ANNOCURSADO" NUMBER,
	"ANNOTERMINADO" NUMBER,
	"HULTIMOGRADO" NUMBER,
	"HIJOSNAC_V" NUMBER,
	"HIJOSNAC_M" NUMBER,
	"FECHAOPERACION" DATE,
	"LOGIN" VARCHAR2(10),
	"SABELEER" VARCHAR2(1),
	"HESTADOCIVIL" NUMBER,
	"HIJOSNAC_AV" NUMBER,
	"HIJOSNAC_MF" NUMBER,
	"HLOCARESIDENCIA" NUMBER,
	"DIRECRESIDENCIA" VARCHAR2(200),
	"HLOCARESIDENCIAFP" NUMBER
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_MORTVIOL =====

  CREATE TABLE "TEMP"."T_MORTVIOL"
   (	"ID" NUMBER,
	"HCERTIFICADO" NUMBER NOT NULL ENABLE,
	"HTIPO_M" NUMBER,
	"HORA_MV" VARCHAR2(20),
	"FECHA_MV" DATE,
	"DESCRIPCIONSUCESO" VARCHAR2(400),
	"HLUGARSUCESO" NUMBER,
	"LOGIN" VARCHAR2(10),
	"FECHAOPERACION" DATE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_MRESPA =====

  CREATE TABLE "TEMP"."T_MRESPA"
   (	"ID" FLOAT(126) NOT NULL ENABLE,
	"SID" VARCHAR2(10) NOT NULL ENABLE,
	"FECHA" DATE NOT NULL ENABLE,
	"TEXTO_FECHA" VARCHAR2(20) NOT NULL ENABLE,
	"HDD_BD_USADO" VARCHAR2(10) NOT NULL ENABLE,
	"HDD_BD_SIZE" VARCHAR2(10) NOT NULL ENABLE,
	"HDD_BK_USADO" VARCHAR2(10) NOT NULL ENABLE,
	"HDD_BK_SIZE" VARCHAR2(10) NOT NULL ENABLE,
	"HDD_OPT_USADO" VARCHAR2(10) NOT NULL ENABLE,
	"HDD_OPT_SIZE" VARCHAR2(10) NOT NULL ENABLE,
	"TAM_RESPALDO_DMP" VARCHAR2(10) NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_NOTDSP04 =====

  CREATE TABLE "TEMP"."T_NOTDSP04"
   (	"ID" FLOAT(126) NOT NULL ENABLE,
	"DOCUMENTO" FLOAT(126) NOT NULL ENABLE,
	"ACTIVIDAD" FLOAT(126) NOT NULL ENABLE,
	"NOTA" VARCHAR2(2000) NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_ORGGEOG =====

  CREATE TABLE "TEMP"."T_ORGGEOG"
   (	"NUM_REGION" NUMBER(10,0) NOT NULL ENABLE,
	"COD_CATEGORIA" NUMBER(3,0),
	"REGION_PRECEDENTE" NUMBER(10,0),
	"DES_REGION" VARCHAR2(150) NOT NULL ENABLE,
	"COD_OCEI" VARCHAR2(30),
	"CAN_CASAS" NUMBER(7,0),
	"POBLACION_ESTIMADA" NUMBER(8,0),
	"GAC_GIS_LAT" VARCHAR2(18),
	"GAC_GIS_LONG" VARCHAR2(18),
	"GAC_GIS_PROJ" NUMBER(3,0),
	"GAC_GIS_TAGX" NUMBER(14,4),
	"GAC_GIS_TAGY" NUMBER(14,4),
	"GAC_GIS_TAGF" NUMBER(2,0),
	"GAC_GIS_TAGT" VARCHAR2(1),
	"GAC_GIS_TAGH" NUMBER(8,2),
	"GAC_GIS_TAGC" NUMBER(2,0),
	"GAC_GIS_TAGR" NUMBER(8,3),
	"GAC_GIS_PCOL" NUMBER(3,0),
	"GAC_GIS_LIB" VARCHAR2(50),
	"GAC_CLAV_LOC" VARCHAR2(9),
	"GAC_CLA_OCEI" VARCHAR2(10),
	"GAC_NOMBRE" VARCHAR2(40),
	"GAC_GENERICO" VARCHAR2(4),
	"GAC_LATITUD" VARCHAR2(6),
	"GAC_LONGITUD" VARCHAR2(6),
	"GAC_UBIC_POLIT" VARCHAR2(6),
	"GAC_ESTADO" VARCHAR2(2),
	"GAC_MUN_DIS" VARCHAR2(2),
	"GAC_FOR_PAR" VARCHAR2(2),
	"GAC_LOCALIDAD" VARCHAR2(3),
	"GAC_CARTA" VARCHAR2(4),
	"GAC_CUADRICULA" VARCHAR2(6),
	"COD_ESTADO" VARCHAR2(20),
	"OBS_REGION" VARCHAR2(250),
	"CLAVE_CTRL" NUMBER(10,0),
	"EDO_CTRL" NUMBER(10,0),
	"CODIGOINTERNO" VARCHAR2(25),
	"NOMBRELARGO" VARCHAR2(500),
	"COD_INE" VARCHAR2(14),
	"ESTATUS" NUMBER
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_OTROTRAT =====

  CREATE TABLE "TEMP"."T_OTROTRAT"
   (	"ID" NUMBER NOT NULL ENABLE,
	"HFICHAS_EPIDEMIOLOGICAS" NUMBER,
	"HPROGRAMA" NUMBER,
	"TRATAMIENTO" VARCHAR2(100),
	"NRO_UNIDADES" NUMBER,
	"INDICACIONES" VARCHAR2(100),
	"USUARIO" VARCHAR2(10),
	"FECHAOPERACION" DATE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_PACCONDE =====

  CREATE TABLE "TEMP"."T_PACCONDE"
   (	"ID" FLOAT(126) NOT NULL ENABLE,
	"HPACIENTE" FLOAT(126) NOT NULL ENABLE,
	"HCONDICIONESPECIAL" FLOAT(126) NOT NULL ENABLE,
	"USUARIO" VARCHAR2(15),
	"FECHAOPERACION" DATE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_PACIEND =====

  CREATE TABLE "TEMP"."T_PACIEND"
   (	"ID" FLOAT(126) NOT NULL ENABLE,
	"NUMERO" VARCHAR2(15),
	"CEDULA" VARCHAR2(20),
	"NOMBRE" VARCHAR2(100),
	"SEXO" FLOAT(126),
	"EDAD" FLOAT(126),
	"TIPOEDAD" FLOAT(126),
	"DIRECCION" VARCHAR2(254),
	"FECHA" DATE,
	"HLOCALIDAD" FLOAT(126) NOT NULL ENABLE,
	"ORIGEN" FLOAT(126) NOT NULL ENABLE,
	"SEMANA" FLOAT(126),
	"ANNO" FLOAT(126),
	"TIPODENGUE" FLOAT(126),
	"ASISTENCIA" FLOAT(126),
	"MUERTE" FLOAT(126),
	"FECHACREACION" DATE,
	"USUARIO" VARCHAR2(15)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_PACIENFE =====

  CREATE TABLE "TEMP"."T_PACIENFE"
   (	"ID" FLOAT(126) NOT NULL ENABLE,
	"NROHISTORIA" VARCHAR2(20),
	"CEDULA" VARCHAR2(12),
	"NOMBREPACIENTE" VARCHAR2(25),
	"APELLIDOPACIENTE" VARCHAR2(25),
	"FECHANACIMIENTO" DATE,
	"EDAD" FLOAT(126),
	"UNIDAD_EDAD" CHAR(1),
	"LUGAR_NAC" VARCHAR2(50),
	"SEXO" NUMBER,
	"DIRECCIONHABITUAL" VARCHAR2(254),
	"HUBICACION" NUMBER(10,0),
	"TIEMPO_RESIDENCIA" VARCHAR2(10),
	"TELEFONOH" VARCHAR2(12),
	"LOCALIZACION" VARCHAR2(254),
	"HLOCALIZACION" NUMBER(10,0),
	"OTRO_TIEMPO_RES" VARCHAR2(10),
	"TELEFONOL" VARCHAR2(12),
	"HETNIA" FLOAT(126),
	"HCONYUGAL" FLOAT(126),
	"HOCUPACION" FLOAT(126),
	"ANALFABETA" VARCHAR2(2),
	"HULTIMOGRADO" FLOAT(126),
	"ANOS_APROBADOS" NUMBER(2,0),
	"USUARIO" VARCHAR2(10),
	"FECHAOPERACION" DATE,
	"NOMREPRESENTANTE" VARCHAR2(40),
	"NUMERO_HIJO" VARCHAR2(2),
	"FECHADEFUNCION" DATE,
	"NACIONALIDAD" VARCHAR2(1)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_PACIENTT =====

  CREATE TABLE "TEMP"."T_PACIENTT"
   (	"USUARIO" VARCHAR2(10),
	"ID" FLOAT(126) NOT NULL ENABLE,
	"FECHAREGISTRO" DATE,
	"HCENTROASISTENCIAL" FLOAT(126),
	"NROHISTORIA" VARCHAR2(20),
	"NOMBREPACIENTE" VARCHAR2(50),
	"FECHANACIMIENTO" DATE,
	"EDAD" FLOAT(126),
	"CEDULA" VARCHAR2(12),
	"DIRECCIONHABITUAL" VARCHAR2(100),
	"HUBICACION" FLOAT(126),
	"TELEFONOH" VARCHAR2(12),
	"LOCALIZACION" VARCHAR2(254),
	"TELEFONOL" VARCHAR2(12),
	"HLOCALIZACION" FLOAT(126)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_PACIMISI =====

  CREATE TABLE "TEMP"."T_PACIMISI"
   (	"ID" FLOAT(126) NOT NULL ENABLE,
	"HPACIENTE" FLOAT(126),
	"HMISION" FLOAT(126),
	"FECHAOPERACION" DATE,
	"USUARIO" VARCHAR2(15)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_PERQUIR =====

  CREATE TABLE "TEMP"."T_PERQUIR"
   (	"ID" NUMBER NOT NULL ENABLE,
	"HREGISTROCIRUGIA" NUMBER NOT NULL ENABLE,
	"HROLMEDICO" NUMBER NOT NULL ENABLE,
	"HMEDICO" NUMBER NOT NULL ENABLE,
	"USUARIO" VARCHAR2(10),
	"FECHAOPERACION" DATE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_PERSMEDI =====

  CREATE TABLE "TEMP"."T_PERSMEDI"
   (	"ID" FLOAT(126) NOT NULL ENABLE,
	"CODIGO" VARCHAR2(8) NOT NULL ENABLE,
	"NOMBRE" VARCHAR2(50),
	"CODIGOSAS" VARCHAR2(12),
	"CEDULA" VARCHAR2(12),
	"DIRECCION" VARCHAR2(100),
	"HLOCALIDAD" FLOAT(126),
	"TELEFONOS" VARCHAR2(35),
	"CARGO" VARCHAR2(50),
	"HESTABLECIMIENTO" FLOAT(126),
	"LOGIN" VARCHAR2(10),
	"FECHAOPERACION" DATE,
	"HCARGO" FLOAT(126)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_POBESTA =====

  CREATE TABLE "TEMP"."T_POBESTA"
   (	"ID" FLOAT(126) NOT NULL ENABLE,
	"HESTABLECIMIENTO" FLOAT(126) NOT NULL ENABLE,
	"POB_TOTAL" FLOAT(126),
	"ANNO" FLOAT(126),
	"COBERTURA" FLOAT(126),
	"DISTRIBUCION" FLOAT(126),
	"POBCOBERTURA" FLOAT(126)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_PRODIABE =====

  CREATE TABLE "TEMP"."T_PRODIABE"
   (	"ID" NUMBER NOT NULL ENABLE,
	"HFICHAS_EPIDEMIOLOGICAS" NUMBER NOT NULL ENABLE,
	"HPERSONALMEDICO" NUMBER,
	"ANOINICIO" NUMBER,
	"HCARGO" NUMBER,
	"USUARIO" VARCHAR2(10),
	"FECHAOPERACION" DATE,
	"HCLASIF_CONSULTANTE_PROG" NUMBER,
	"HPREDIABETICO" NUMBER
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_PROGCARD =====

  CREATE TABLE "TEMP"."T_PROGCARD"
   (	"ID" NUMBER NOT NULL ENABLE,
	"HFICHAS_EPIDEMIOLOGICAS" NUMBER NOT NULL ENABLE,
	"HPERSONALMEDICO" NUMBER,
	"ANOINICIO" NUMBER,
	"HCARGO" NUMBER,
	"USUARIO" VARCHAR2(10),
	"FECHAOPERACION" DATE,
	"HCLASIF_CONSULTANTE_PROG" NUMBER,
	"INFARTADO" NUMBER,
	"OBSERVACION" VARCHAR2(2000)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_PROGMCHE =====

  CREATE TABLE "TEMP"."T_PROGMCHE"
   (	"ID" FLOAT(126) NOT NULL ENABLE,
	"HFICHA_EPIDEMIOLOGICA" FLOAT(126),
	"OTRAS_BASES_DIAG" VARCHAR2(100),
	"NRO_MUESTRA" VARCHAR2(20),
	"FECHA_TOMA" DATE,
	"LUGAR_TOMA" VARCHAR2(100),
	"FECH_INIT_FIEBRE" DATE,
	"LUGAR_INICIO_FIEBRE" VARCHAR2(50),
	"PERMANENCIA_LUG_FIEBRE" VARCHAR2(20),
	"HCONDICION_INGRESO_MALARIA" FLOAT(126),
	"OTROS_TRATAMIENTOS" VARCHAR2(250),
	"HUBICACION_INFECCION" NUMBER(10,0),
	"HPAIS" FLOAT(126),
	"TRANF_SANGRE" CHAR(1),
	"TRATAM_ENDOVENOSO" CHAR(1),
	"FECHA_TRANF" DATE,
	"HESTAB_TRANF" FLOAT(126),
	"HCLASIF_CONSULTANTE_PROG" FLOAT(126),
	"FECHA_RESULT" DATE,
	"HRESULTADOS_PROG" FLOAT(126),
	"HPERSONALMEDICO" FLOAT(126),
	"HCARGO" FLOAT(126),
	"COMPLICACIONES" VARCHAR2(250),
	"OBSERVACIONES" VARCHAR2(4000),
	"USUARIO" VARCHAR2(10),
	"FECHAOPERACION" DATE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_PROGTUBE =====

  CREATE TABLE "TEMP"."T_PROGTUBE"
   (	"ID" NUMBER NOT NULL ENABLE,
	"HFICHAS_EPIDEMIOLOGICAS" NUMBER NOT NULL ENABLE,
	"HPACIENTE" NUMBER NOT NULL ENABLE,
	"SERIE" VARCHAR2(1),
	"CASONUMERO" VARCHAR2(9),
	"COHORTE" VARCHAR2(1),
	"FECHANOTIFICACION" DATE,
	"HCONDICIONCASO" NUMBER,
	"SEROLOGIAVIH" NUMBER,
	"BACTERIOLOGIA" NUMBER,
	"CLINICA" NUMBER,
	"RADIOLOGIA" NUMBER,
	"RESRADIOLOGIA" NUMBER,
	"CAVERNA" NUMBER,
	"HISTOLOGIA" NUMBER,
	"TUBERCULINA" NUMBER,
	"HDIAGNOSTICO" NUMBER,
	"LOCALIZACION" NUMBER,
	"RESLOCALIZACION" NUMBER,
	"HPERSONALMEDICO" NUMBER,
	"HCARGO" NUMBER,
	"HMEDICOCOORD" NUMBER,
	"USUARIO" VARCHAR2(10),
	"FECHAOPERACION" DATE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_PROTTROM =====

  CREATE TABLE "TEMP"."T_PROTTROM"
   (	"ID" NUMBER NOT NULL ENABLE,
	"HFICHA_PROGRAMA" NUMBER NOT NULL ENABLE,
	"INFARTOPREVIO" NUMBER,
	"TIEMPOUTIL" VARCHAR2(2),
	"TRATAMIENTOTROMBO" NUMBER,
	"LI_PRE_TROMBO" NUMBER,
	"LI_POST_TROMBO" NUMBER,
	"LI_ENZIMA_PRE_T" NUMBER,
	"LI_POST_T" NUMBER,
	"ESTANCIA" NUMBER,
	"ESTUDIONOINVASIVO" NUMBER,
	"HEMODINAMIA" NUMBER,
	"CIRUGIA" NUMBER,
	"UCC" NUMBER,
	"UTI" NUMBER,
	"HOSPITALIZACION" NUMBER,
	"D_EGRESO" NUMBER,
	"D_MORGE" NUMBER,
	"D_OTROSERVICIO" NUMBER,
	"SISTOLICA" NUMBER,
	"DIASTOLICA" NUMBER,
	"HORA_INICIADOLOR" VARCHAR2(10),
	"HORA_ASISTENCIA" VARCHAR2(10),
	"HORA_INGRESOHOSP" VARCHAR2(10),
	"EVALTRATAMIENTO" NUMBER,
	"CUALCOMPLICACION" VARCHAR2(50),
	"DONDEHOSPITALIZACION" VARCHAR2(50),
	"HCENTROREFERENCIA" NUMBER,
	"LOCALIZAINFARTO" NUMBER,
	"REFERIDOOTROSERVICIO" VARCHAR2(50)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_PRVIHSID =====

  CREATE TABLE "TEMP"."T_PRVIHSID"
   (	"ID" NUMBER NOT NULL ENABLE,
	"HFICHAS_EPIDEMIOLOGICAS" FLOAT(126),
	"EDAD_GESTACIONAL" NUMBER,
	"NRO_HIJOS" NUMBER,
	"EDAD_ULT_HIJO" NUMBER,
	"HTRANSMISION_POR" NUMBER,
	"HMEDIO_TRANSMISION" NUMBER,
	"OTRAS_BASES_DIAG" VARCHAR2(100),
	"HCONDICION_INGRESO" FLOAT(126),
	"HACTIVIDAD_OSP" FLOAT(126),
	"OTROS_TRATAMIENTOS" VARCHAR2(250),
	"HPERSONALMEDICO" FLOAT(126),
	"HCARGO" FLOAT(126),
	"COMPLICACIONES" VARCHAR2(4000),
	"OBSERVACIONES" VARCHAR2(4000),
	"USUARIO" VARCHAR2(10),
	"FECHAOPERACION" DATE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_RCASOSMI =====

  CREATE TABLE "TEMP"."T_RCASOSMI"
   (	"ID" NUMBER NOT NULL ENABLE,
	"HCASOSMMI" NUMBER NOT NULL ENABLE,
	"HOCURRENCIA" NUMBER NOT NULL ENABLE,
	"HSITIO_OCURRENCIA" NUMBER,
	"HESTABLECIMIENTO" NUMBER,
	"HCAUSA_CIE10" NUMBER,
	"EDAD_GESTACIONAL" NUMBER,
	"CONTROL_PRENATAL" NUMBER,
	"PESO" FLOAT(126),
	"FECHAOPERACION" DATE,
	"USUARIO" VARCHAR2(10),
	"HCAUSABAS_CIE10" NUMBER,
	"HNUTRICION" NUMBER,
	"ESTANCIAHOSP" NUMBER
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_RCASOSMM =====

  CREATE TABLE "TEMP"."T_RCASOSMM"
   (	"ID" NUMBER NOT NULL ENABLE,
	"HCASOSMMI" NUMBER NOT NULL ENABLE,
	"HOCURRENCIA" NUMBER NOT NULL ENABLE,
	"HSITIO_OCURRENCIA" NUMBER,
	"HESTABLECIMIENTO" NUMBER,
	"HCAUSA_CIE10" NUMBER,
	"EDAD_GESTACIONAL" NUMBER,
	"CONTROL_PRENATAL" NUMBER,
	"HFORMAPARTO" NUMBER,
	"HANEXOSPERIODO" NUMBER,
	"FECHAOPERACION" DATE,
	"USUARIO" VARCHAR2(10),
	"PERIODOOCURRENCIA" NUMBER,
	"HCAUSABAS_CIE10" NUMBER
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_REGCIRU =====

  CREATE TABLE "TEMP"."T_REGCIRU"
   (	"ID" NUMBER NOT NULL ENABLE,
	"HESTABLECIMIENTO" NUMBER NOT NULL ENABLE,
	"HPACIENTE" NUMBER NOT NULL ENABLE,
	"INTERV_HOSP_AMB" NUMBER NOT NULL ENABLE,
	"FECHA_INTERV" DATE NOT NULL ENABLE,
	"FECHA_INGRESO" DATE,
	"FECHA_SALIDA" DATE,
	"USUARIO" VARCHAR2(10),
	"FECHAOPERACION" DATE,
	"NUMERO_HISTORIA" VARCHAR2(20),
	"HOSPITAL_ELECT_EMERG" NUMBER,
	"REFERIDO_CENTRO" NUMBER,
	"REFERIDO_SERVICIO" NUMBER,
	"QUIROFANO" NUMBER,
	"TOMA_MUESTRA" VARCHAR2(200),
	"INTERVENCION_OMITIDA" NUMBER,
	"OTRAINTERVENCION_OMITIDA" VARCHAR2(100),
	"CAUSA_EGRESO" NUMBER,
	"OBSERVACION" VARCHAR2(200)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_REGVACU =====

  CREATE TABLE "TEMP"."T_REGVACU"
   (	"ID" FLOAT(126) NOT NULL ENABLE,
	"HESTABLECIMIENTO" FLOAT(126) NOT NULL ENABLE,
	"HACTIVIDAD" FLOAT(126) NOT NULL ENABLE,
	"HPACIENTE" FLOAT(126) NOT NULL ENABLE,
	"HPACIENTEMISION" FLOAT(126),
	"EMBARAZADA" FLOAT(126),
	"LOTE" VARCHAR2(30),
	"FECHA" DATE,
	"TIPOEDAD2" VARCHAR2(1),
	"EDAD2" FLOAT(126),
	"FECHAOPERACION" DATE,
	"USUARIO" VARCHAR2(15),
	"HPAC_COND_ESPE" NUMBER
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_RENDSP04 =====

  CREATE TABLE "TEMP"."T_RENDSP04"
   (	"ID" FLOAT(126) NOT NULL ENABLE,
	"DOCUMENTO" FLOAT(126) NOT NULL ENABLE,
	"ACTIVIDAD" FLOAT(126) NOT NULL ENABLE,
	"REALIZADO" FLOAT(126)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_RENEPI15 =====

  CREATE TABLE "TEMP"."T_RENEPI15"
   (	"ID" FLOAT(126) NOT NULL ENABLE,
	"DOCUMENTO" FLOAT(126) NOT NULL ENABLE,
	"ENFERMEDAD" FLOAT(126) NOT NULL ENABLE,
	"CASOSX" FLOAT(126),
	"CASOSP" FLOAT(126),
	"CASOSS" FLOAT(126),
	"FECHAOPERACION" DATE,
	"USUARIO" VARCHAR2(15)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_RENGRES =====

  CREATE TABLE "TEMP"."T_RENGRES"
   (	"ID" FLOAT(126) NOT NULL ENABLE,
	"HRESUMEN" FLOAT(126) NOT NULL ENABLE,
	"HTIPOESTABLE" FLOAT(126) NOT NULL ENABLE,
	"CANT_ESTABLE" FLOAT(126) NOT NULL ENABLE,
	"CANT_DOCUMENTO" FLOAT(126) NOT NULL ENABLE,
	"USUARIO" VARCHAR2(15),
	"FECHAOPERACION" DATE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_RENGSIT =====

  CREATE TABLE "TEMP"."T_RENGSIT"
   (	"ID" FLOAT(126) NOT NULL ENABLE,
	"HRESUMEN" FLOAT(126) NOT NULL ENABLE,
	"HCODIFICADOR" FLOAT(126) NOT NULL ENABLE,
	"HLOCALIDAD" FLOAT(126) NOT NULL ENABLE,
	"CANT_CASOS" FLOAT(126) NOT NULL ENABLE,
	"CANT_MUERTES" FLOAT(126) NOT NULL ENABLE,
	"TIPOSITUACION" FLOAT(126) NOT NULL ENABLE,
	"USUARIO" VARCHAR2(15),
	"FECHAOPERACION" DATE,
	"GRAVE" NUMBER,
	"INUSITADO" NUMBER,
	"NACIONAL" NUMBER,
	"INTERNAC" NUMBER,
	"FECHAINICIO" DATE,
	"FECHAFIN" DATE,
	"HESTABLECIMIENTO" NUMBER
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_RENGTELE =====

  CREATE TABLE "TEMP"."T_RENGTELE"
   (	"ID" FLOAT(126) NOT NULL ENABLE,
	"DOCUMENTO" FLOAT(126) NOT NULL ENABLE,
	"ENFERMEDAD" FLOAT(126) NOT NULL ENABLE,
	"EDAD" FLOAT(126) NOT NULL ENABLE,
	"CASOS" FLOAT(126),
	"MUERTES" FLOAT(126),
	"USUARIO" VARCHAR2(15),
	"FECHAOPERACION" DATE,
	"CASOSHOM" NUMBER,
	"CASOSMUJ" NUMBER,
	"MUERTESHOM" NUMBER,
	"MUERTESMUJ" NUMBER
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_RESUMEN =====

  CREATE TABLE "TEMP"."T_RESUMEN"
   (	"ID" FLOAT(126) NOT NULL ENABLE,
	"HESTABLECIMIENTO" FLOAT(126) NOT NULL ENABLE,
	"HCATEGORIA" FLOAT(126) NOT NULL ENABLE,
	"PERIODO" FLOAT(126) NOT NULL ENABLE,
	"ANNO" FLOAT(126) NOT NULL ENABLE,
	"SITUACION_ESPECIAL" VARCHAR2(4000),
	"USUARIO" VARCHAR2(15),
	"FECHAOPERACION" DATE,
	"OBSERVACION" VARCHAR2(2000)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_RNACANUL =====

  CREATE TABLE "TEMP"."T_RNACANUL"
   (	"ID" NUMBER NOT NULL ENABLE,
	"HESTABLECIMIENTO" NUMBER NOT NULL ENABLE,
	"NROPLANILLA" VARCHAR2(20) NOT NULL ENABLE,
	"CONSECUTIVO" VARCHAR2(20) NOT NULL ENABLE,
	"ANO_CERTIF" NUMBER,
	"FECHA_ANULADO" DATE,
	"CAUSA_ANULADO" VARCHAR2(200) NOT NULL ENABLE,
	"USUARIO" VARCHAR2(10),
	"HCAUSAANULADO" NUMBER NOT NULL ENABLE,
	"FECHA_OPERACION" DATE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_RNACNACI =====

  CREATE TABLE "TEMP"."T_RNACNACI"
   (	"ID" FLOAT(126),
	"HCERTIFICADO" FLOAT(126) NOT NULL ENABLE,
	"HISTORIACLINICA" VARCHAR2(20),
	"NOMBRES" VARCHAR2(100),
	"FECHANACIMIENTO" DATE,
	"HORA" VARCHAR2(10),
	"PESO" FLOAT(126),
	"TALLA" FLOAT(126),
	"HSEXO" FLOAT(126),
	"HTIPOPARTO" FLOAT(126),
	"HASISTENCIA" FLOAT(126),
	"OBSERVACION" VARCHAR2(200),
	"HLOCALIDAD" FLOAT(126),
	"HSITIOPARTO" FLOAT(126),
	"FECHAOPERACION" DATE,
	"USUARIO" VARCHAR2(15),
	"SEMANAGESTACION" NUMBER,
	"HFORMAPARTO" NUMBER,
	"VIVO_MUERTO" NUMBER(1,0),
	"OCURREPARTOOTRO" VARCHAR2(60),
	"ATENDIOPARTOOTRO" VARCHAR2(60)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_SEGDIABE =====

  CREATE TABLE "TEMP"."T_SEGDIABE"
   (	"ID" NUMBER NOT NULL ENABLE,
	"HFICHAS_EPIDEMIOLOGICAS" NUMBER NOT NULL ENABLE,
	"HCENTROASISTENCIAL" NUMBER,
	"FECHAEVOLUCION" DATE,
	"HCLASIF_CONSULTANTE_PROG" NUMBER,
	"NUMSECCIONES" NUMBER,
	"IMC" NUMBER,
	"GLICEMIA" NUMBER,
	"TENSIONARTERIAL_ALTA" NUMBER,
	"TENSIONARTERIAL_BAJA" NUMBER,
	"GLICOSILADA" NUMBER,
	"COLESTEROL" NUMBER,
	"MICROALBUM" NUMBER,
	"CREATININA" NUMBER,
	"TRIGLICERIDO" NUMBER,
	"LDL" NUMBER,
	"HDL" NUMBER,
	"DEPCREATININA" NUMBER,
	"FONDODEOJO" NUMBER,
	"CAUSASHOSPITALARIAS" VARCHAR2(250),
	"SESIONEDUCATIVA" VARCHAR2(100),
	"SECCIONES" NUMBER,
	"EGRESO" NUMBER,
	"CONDICIONEGRESO" NUMBER,
	"HLOCALIDAD_TRANF" NUMBER,
	"HLOCALIDAD_SEG" NUMBER,
	"FECHATRANSFERENCIA" DATE,
	"CAUSADEMUERTE" VARCHAR2(1),
	"HPERSONALMEDICO" NUMBER,
	"HCARGO" NUMBER,
	"FLUORO" NUMBER,
	"USUARIO" VARCHAR2(10),
	"FECHAOPERACION" DATE,
	"EVALUACION" VARCHAR2(4000),
	"HESPECIALIDAD" NUMBER
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_SEGEVOLP =====

  CREATE TABLE "TEMP"."T_SEGEVOLP"
   (	"ID" FLOAT(126) NOT NULL ENABLE,
	"HFICHAS_EPIDEMIOLOGICAS" FLOAT(126),
	"FECHA_SEG" DATE NOT NULL ENABLE,
	"HESTABLECIMIENTO" FLOAT(126),
	"HLOCALIDAD_SEG" NUMBER(10,0),
	"FECHA_RESULT_SEG" DATE,
	"OTROS_TRATAM_SEG" VARCHAR2(250),
	"COMPLICACION_SEG" VARCHAR2(250),
	"OBSERVACION_SEG" VARCHAR2(4000),
	"HEVOLUCION" FLOAT(126),
	"HPERSONALMEDICO" FLOAT(126),
	"HCARGO" FLOAT(126),
	"USUARIO" VARCHAR2(10),
	"FECHAOPERACION" DATE,
	"HRESULTADOS_PROG" FLOAT(126),
	"HPROG_M_CH_E" NUMBER
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_SEGUCARD =====

  CREATE TABLE "TEMP"."T_SEGUCARD"
   (	"ID" NUMBER NOT NULL ENABLE,
	"HFICHAS_EPIDEMIOLOGICAS" NUMBER NOT NULL ENABLE,
	"HCENTROASISTENCIAL" NUMBER,
	"HLOCALIDAD_SEG" NUMBER,
	"HPERSONALMEDICO" NUMBER,
	"HCARGO" NUMBER,
	"EVALUACION" VARCHAR2(4000),
	"USUARIO" VARCHAR2(10),
	"FECHAEVOLUCION" DATE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_SIGNSINT =====

  CREATE TABLE "TEMP"."T_SIGNSINT"
   (	"ID" FLOAT(126) NOT NULL ENABLE,
	"HFICHAS_EPIDEMIOLOGICAS" FLOAT(126),
	"HRELACION_PROG_BASESD" FLOAT(126) NOT NULL ENABLE,
	"USUARIO" VARCHAR2(10),
	"FECHAOPERACION" DATE,
	"HPROG_M_CH_E" NUMBER
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_SIGSINSE =====

  CREATE TABLE "TEMP"."T_SIGSINSE"
   (	"ID" NUMBER NOT NULL ENABLE,
	"HFICHAS_EPIDEMIOLOGICAS" NUMBER,
	"HRELACION_PROG_BASESD" NUMBER,
	"USUARIO" VARCHAR2(10),
	"FECHAOPERACION" DATE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_SITUESPE =====

  CREATE TABLE "TEMP"."T_SITUESPE"
   (	"ID" NUMBER NOT NULL ENABLE,
	"HRESUMEN" NUMBER NOT NULL ENABLE,
	"HTIPOEVENTO" NUMBER NOT NULL ENABLE,
	"HLOCALIDAD" NUMBER NOT NULL ENABLE,
	"CANT_CASOS" NUMBER,
	"CANT_MUERTES" NUMBER,
	"MEDIDATOMADA" VARCHAR2(200),
	"DESCRIPCIONEVENTO" VARCHAR2(200),
	"FECHAOPERACION" DATE,
	"USUARIO" VARCHAR2(10)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_TRASEGIM =====

  CREATE TABLE "TEMP"."T_TRASEGIM"
   (	"ID" NUMBER NOT NULL ENABLE,
	"HFICHAS_EPIDEMIOLOGICAS" NUMBER,
	"HRELACION_PROG_TRATAM" NUMBER,
	"NRO_UNIDADES" NUMBER,
	"USUARIO" VARCHAR2(10),
	"FECHAOPERACION" DATE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_TRATAMIE =====

  CREATE TABLE "TEMP"."T_TRATAMIE"
   (	"ID" FLOAT(126) NOT NULL ENABLE,
	"HFICHAS_EPIDEMIOLOGICAS" FLOAT(126),
	"HRELACION_PROG_TRATAM" FLOAT(126),
	"HSEG_EVOL_PACIENTE" FLOAT(126),
	"USUARIO" VARCHAR2(10),
	"FECHAOPERACION" DATE,
	"NRO_UNIDADES" NUMBER,
	"HPROG_M_CH_E" NUMBER
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_TRATUBER =====

  CREATE TABLE "TEMP"."T_TRATUBER"
   (	"ID" NUMBER NOT NULL ENABLE,
	"HFICHAS_EPIDEMIOLOGICAS" NUMBER NOT NULL ENABLE,
	"INICIOTRA" NUMBER,
	"FECHAINICIOTRA" DATE,
	"MESESTRAT_I" NUMBER,
	"MESESTRAT_M" NUMBER,
	"ADMINISTRACIONTRA" NUMBER,
	"NOTAES" VARCHAR2(100),
	"RESULTADOBACT_1" NUMBER,
	"RESULTADOBACT_2" NUMBER,
	"RESULTADOBACT_3" NUMBER,
	"RESULTADOBACT_4" NUMBER,
	"RESULTADOBACT_5" NUMBER,
	"RESULTADOBACT_6" NUMBER,
	"RESULTADOBACT_F" NUMBER,
	"EGRESO" NUMBER,
	"REINGRESO" NUMBER,
	"FECHAEGRESO" DATE,
	"FECHAREINGRESO" DATE,
	"HCONDICIONFINALEGRESO" NUMBER,
	"HCONDICIONFINALREINGRESO" NUMBER(1,0),
	"MUERTETB" NUMBER,
	"MUERTEOTRACAUSA" NUMBER,
	"SEMANA_ABANDONO" NUMBER,
	"LUGARTRANSFERENCIA" NUMBER,
	"OBSERVACION" VARCHAR2(2000),
	"TOMASPROGRAMADAS" NUMBER,
	"TOMASCUMPLIDAS" NUMBER,
	"USUARIO" VARCHAR2(10),
	"FECHAOPERACION" DATE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_TSEGCARD =====

  CREATE TABLE "TEMP"."T_TSEGCARD"
   (	"ID" NUMBER NOT NULL ENABLE,
	"HFICHAS_EPIDEMIOLOGICAS" NUMBER,
	"HRELACION_PROG_TRATAM" NUMBER,
	"NRO_UNIDADES" NUMBER,
	"USUARIO" VARCHAR2(10),
	"FECHAOPERACION" DATE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== T_USUARIOS =====

  CREATE TABLE "TEMP"."T_USUARIOS"
   (	"LOGIN" VARCHAR2(10) NOT NULL ENABLE,
	"PASSWORD" VARCHAR2(12) NOT NULL ENABLE,
	"NOMBRE" VARCHAR2(40),
	"CEDULA" VARCHAR2(10),
	"CARGO" VARCHAR2(150),
	"JERARQUIA" VARCHAR2(2),
	"CREADO" VARCHAR2(10),
	"FEC_CREA" DATE,
	"FEC_ENT" DATE,
	"ID" FLOAT(126),
	"ESTATUS" NUMBER,
	"HESTABLECIMIENTO" NUMBER,
	"MORBILIDAD" NUMBER,
	"NATALIDAD" NUMBER,
	"MORTALIDAD" NUMBER,
	"ONCOLOGIA" NUMBER,
	"FICHAS" NUMBER,
	"ACCIDENTE" NUMBER,
	"CIRUGIA" NUMBER,
	"VACUNACION" NUMBER,
	"TRANSFERENCIA" NUMBER
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_ID36 de T_ACCILABO =====

  CREATE INDEX "TEMP"."INF_ID36" ON "TEMP"."T_ACCILABO" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_ID59 de T_ACCTRANS =====

  CREATE INDEX "TEMP"."INF_ID59" ON "TEMP"."T_ACCTRANS" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_ID67 de T_ALABCARD =====

  CREATE INDEX "TEMP"."INF_ID67" ON "TEMP"."T_ALABCARD" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_ID32 de T_ANALABOR =====

  CREATE INDEX "TEMP"."INF_ID32" ON "TEMP"."T_ANALABOR" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_ID31 de T_ANTEFACT =====

  CREATE INDEX "TEMP"."INF_ID31" ON "TEMP"."T_ANTEFACT" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_ID78 de T_AUDITORIA =====

  CREATE INDEX "TEMP"."INF_ID78" ON "TEMP"."T_AUDITORIA" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_ID24 de T_BIOPSEG =====

  CREATE INDEX "TEMP"."INF_ID24" ON "TEMP"."T_BIOPSEG" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_ID23 de T_BIOPSIAT =====

  CREATE INDEX "TEMP"."INF_ID23" ON "TEMP"."T_BIOPSIAT" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_ID71 de T_CASOSMM =====

  CREATE INDEX "TEMP"."INF_ID71" ON "TEMP"."T_CASOSMM" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_ID70 de T_CASOSMMI =====

  CREATE INDEX "TEMP"."INF_ID70" ON "TEMP"."T_CASOSMMI" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_CAUMMEDI de T_CAUMMEDI =====

  CREATE INDEX "TEMP"."INF_CAUMMEDI" ON "TEMP"."T_CAUMMEDI" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_ID10 de T_CERTMORT =====

  CREATE INDEX "TEMP"."INF_ID10" ON "TEMP"."T_CERTMORT" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_ID18 de T_CERTNACI =====

  CREATE INDEX "TEMP"."INF_ID18" ON "TEMP"."T_CERTNACI" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_ID51 de T_COMAGUDA =====

  CREATE INDEX "TEMP"."INF_ID51" ON "TEMP"."T_COMAGUDA" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_ID52 de T_COMCRONI =====

  CREATE INDEX "TEMP"."INF_ID52" ON "TEMP"."T_COMCRONI" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_ID53 de T_COMDISCA =====

  CREATE INDEX "TEMP"."INF_ID53" ON "TEMP"."T_COMDISCA" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_ID65 de T_COMPCARD =====

  CREATE INDEX "TEMP"."INF_ID65" ON "TEMP"."T_COMPCARD" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_ID50 de T_COMPLICA =====

  CREATE INDEX "TEMP"."INF_ID50" ON "TEMP"."T_COMPLICA" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_ID47 de T_COMQUIR =====

  CREATE INDEX "TEMP"."INF_ID47" ON "TEMP"."T_COMQUIR" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_ID56 de T_COMSEGIM =====

  CREATE INDEX "TEMP"."INF_ID56" ON "TEMP"."T_COMSEGIM" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_ID29 de T_DIAGASOC =====

  CREATE INDEX "TEMP"."INF_ID29" ON "TEMP"."T_DIAGASOC" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_ID75 de T_DOCUDENG =====

  CREATE INDEX "TEMP"."INF_ID75" ON "TEMP"."T_DOCUDENG" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_ID04 de T_DOCUMENT =====

  CREATE INDEX "TEMP"."INF_ID04" ON "TEMP"."T_DOCUMENT" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_ID74 de T_DOCUSOSP =====

  CREATE INDEX "TEMP"."INF_ID74" ON "TEMP"."T_DOCUSOSP" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_ID02 de T_ESTABLE =====

  CREATE INDEX "TEMP"."INF_ID02" ON "TEMP"."T_ESTABLE" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_EVEFEC de T_EVENTOS =====

  CREATE INDEX "TEMP"."INF_EVEFEC" ON "TEMP"."T_EVENTOS" ("EVENTO", "FECHA")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_EVENTO de T_EVENTOS =====

  CREATE INDEX "TEMP"."INF_EVENTO" ON "TEMP"."T_EVENTOS" ("EVENTO")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_ID1 de T_EVENTOS =====

  CREATE INDEX "TEMP"."INF_ID1" ON "TEMP"."T_EVENTOS" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_TABLA de T_EVENTOS =====

  CREATE INDEX "TEMP"."INF_TABLA" ON "TEMP"."T_EVENTOS" ("TABLA")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_ID63 de T_FDOLORTO =====

  CREATE INDEX "TEMP"."INF_ID63" ON "TEMP"."T_FDOLORTO" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_ID58 de T_FICHAACC =====

  CREATE INDEX "TEMP"."INF_ID58" ON "TEMP"."T_FICHAACC" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_ID26 de T_FICHASEP =====

  CREATE INDEX "TEMP"."INF_ID26" ON "TEMP"."T_FICHASEP" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_ID60 de T_HECHOSVI =====

  CREATE INDEX "TEMP"."INF_ID60" ON "TEMP"."T_HECHOSVI" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_ID46 de T_INTQUIR =====

  CREATE INDEX "TEMP"."INF_ID46" ON "TEMP"."T_INTQUIR" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_ID28 de T_LUGARVIS =====

  CREATE INDEX "TEMP"."INF_ID28" ON "TEMP"."T_LUGARVIS" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_ID19 de T_MADRNACI =====

  CREATE INDEX "TEMP"."INF_ID19" ON "TEMP"."T_MADRNACI" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_IDMBD de T_MBASED =====

  CREATE INDEX "TEMP"."INF_IDMBD" ON "TEMP"."T_MBASED" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_MCAUMORB de T_MCAUMORB =====

  CREATE INDEX "TEMP"."INF_MCAUMORB" ON "TEMP"."T_MCAUMORB" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_ID17 de T_MCAUSMRE =====

  CREATE INDEX "TEMP"."INF_ID17" ON "TEMP"."T_MCAUSMRE" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_ID16 de T_MHOJAREP =====

  CREATE INDEX "TEMP"."INF_ID16" ON "TEMP"."T_MHOJAREP" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_ID15 de T_MORTANUL =====

  CREATE INDEX "TEMP"."INF_ID15" ON "TEMP"."T_MORTANUL" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_ID14 de T_MORTCAUS =====

  CREATE INDEX "TEMP"."INF_ID14" ON "TEMP"."T_MORTCAUS" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_ID13 de T_MORTFETA =====

  CREATE INDEX "TEMP"."INF_ID13" ON "TEMP"."T_MORTFETA" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_ID12 de T_MORTMADR =====

  CREATE INDEX "TEMP"."INF_ID12" ON "TEMP"."T_MORTMADR" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_ID11 de T_MORTVIOL =====

  CREATE INDEX "TEMP"."INF_ID11" ON "TEMP"."T_MORTVIOL" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_MR de T_MRESPA =====

  CREATE INDEX "TEMP"."INF_MR" ON "TEMP"."T_MRESPA" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_ID08 de T_NOTDSP04 =====

  CREATE INDEX "TEMP"."INF_ID08" ON "TEMP"."T_NOTDSP04" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_ID01 de T_ORGGEOG =====

  CREATE INDEX "TEMP"."INF_ID01" ON "TEMP"."T_ORGGEOG" ("NUM_REGION")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_ID57 de T_OTROTRAT =====

  CREATE INDEX "TEMP"."INF_ID57" ON "TEMP"."T_OTROTRAT" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_ID43 de T_PACCONDE =====

  CREATE INDEX "TEMP"."INF_ID43" ON "TEMP"."T_PACCONDE" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_ID76 de T_PACIEND =====

  CREATE INDEX "TEMP"."INF_ID76" ON "TEMP"."T_PACIEND" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_ID25 de T_PACIENFE =====

  CREATE INDEX "TEMP"."INF_ID25" ON "TEMP"."T_PACIENFE" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_ID22 de T_PACIENTT =====

  CREATE INDEX "TEMP"."INF_ID22" ON "TEMP"."T_PACIENTT" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_ID42 de T_PACIMISI =====

  CREATE INDEX "TEMP"."INF_ID42" ON "TEMP"."T_PACIMISI" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_ID45 de T_PERQUIR =====

  CREATE INDEX "TEMP"."INF_ID45" ON "TEMP"."T_PERQUIR" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_ID09 de T_PERSMEDI =====

  CREATE INDEX "TEMP"."INF_ID09" ON "TEMP"."T_PERSMEDI" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_ID03 de T_POBESTA =====

  CREATE INDEX "TEMP"."INF_ID03" ON "TEMP"."T_POBESTA" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_ID48 de T_PRODIABE =====

  CREATE INDEX "TEMP"."INF_ID48" ON "TEMP"."T_PRODIABE" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_ID61 de T_PROGCARD =====

  CREATE INDEX "TEMP"."INF_ID61" ON "TEMP"."T_PROGCARD" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_ID27 de T_PROGMCHE =====

  CREATE INDEX "TEMP"."INF_ID27" ON "TEMP"."T_PROGMCHE" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_ID68 de T_PROGTUBE =====

  CREATE INDEX "TEMP"."INF_ID68" ON "TEMP"."T_PROGTUBE" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_ID64 de T_PROTTROM =====

  CREATE INDEX "TEMP"."INF_ID64" ON "TEMP"."T_PROTTROM" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_ID35 de T_PRVIHSID =====

  CREATE INDEX "TEMP"."INF_ID35" ON "TEMP"."T_PRVIHSID" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_ID73 de T_RCASOSMI =====

  CREATE INDEX "TEMP"."INF_ID73" ON "TEMP"."T_RCASOSMI" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_ID72 de T_RCASOSMM =====

  CREATE INDEX "TEMP"."INF_ID72" ON "TEMP"."T_RCASOSMM" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_ID44 de T_REGCIRU =====

  CREATE INDEX "TEMP"."INF_ID44" ON "TEMP"."T_REGCIRU" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_ID41 de T_REGVACU =====

  CREATE INDEX "TEMP"."INF_ID41" ON "TEMP"."T_REGVACU" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_ID07 de T_RENDSP04 =====

  CREATE INDEX "TEMP"."INF_ID07" ON "TEMP"."T_RENDSP04" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_ID06 de T_RENEPI15 =====

  CREATE INDEX "TEMP"."INF_ID06" ON "TEMP"."T_RENEPI15" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_ID38 de T_RENGRES =====

  CREATE INDEX "TEMP"."INF_ID38" ON "TEMP"."T_RENGRES" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_ID39 de T_RENGSIT =====

  CREATE INDEX "TEMP"."INF_ID39" ON "TEMP"."T_RENGSIT" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_ID05 de T_RENGTELE =====

  CREATE INDEX "TEMP"."INF_ID05" ON "TEMP"."T_RENGTELE" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_ID37 de T_RESUMEN =====

  CREATE INDEX "TEMP"."INF_ID37" ON "TEMP"."T_RESUMEN" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_ID21 de T_RNACANUL =====

  CREATE INDEX "TEMP"."INF_ID21" ON "TEMP"."T_RNACANUL" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_ID20 de T_RNACNACI =====

  CREATE INDEX "TEMP"."INF_ID20" ON "TEMP"."T_RNACNACI" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_ID49 de T_SEGDIABE =====

  CREATE INDEX "TEMP"."INF_ID49" ON "TEMP"."T_SEGDIABE" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_ID34 de T_SEGEVOLP =====

  CREATE INDEX "TEMP"."INF_ID34" ON "TEMP"."T_SEGEVOLP" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_ID62 de T_SEGUCARD =====

  CREATE INDEX "TEMP"."INF_ID62" ON "TEMP"."T_SEGUCARD" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_ID30 de T_SIGNSINT =====

  CREATE INDEX "TEMP"."INF_ID30" ON "TEMP"."T_SIGNSINT" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_ID54 de T_SIGSINSE =====

  CREATE INDEX "TEMP"."INF_ID54" ON "TEMP"."T_SIGSINSE" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_ID40 de T_SITUESPE =====

  CREATE INDEX "TEMP"."INF_ID40" ON "TEMP"."T_SITUESPE" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_ID55 de T_TRASEGIM =====

  CREATE INDEX "TEMP"."INF_ID55" ON "TEMP"."T_TRASEGIM" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_ID33 de T_TRATAMIE =====

  CREATE INDEX "TEMP"."INF_ID33" ON "TEMP"."T_TRATAMIE" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_ID69 de T_TRATUBER =====

  CREATE INDEX "TEMP"."INF_ID69" ON "TEMP"."T_TRATUBER" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_ID66 de T_TSEGCARD =====

  CREATE INDEX "TEMP"."INF_ID66" ON "TEMP"."T_TSEGCARD" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;

-- ===== indice INF_ID77 de T_USUARIOS =====

  CREATE INDEX "TEMP"."INF_ID77" ON "TEMP"."T_USUARIOS" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
;
