# Generated by Django 5.2.17 on 2026-10-03 00:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seguridad', '0004_alter_perfil_rol'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistradorCivil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nacionalidad', models.CharField(choices=[('V', 'Venezolano'), ('E', 'Extranjero'), ('P', 'Pasaporte'), ('I', 'Indocumentado'), ('O', 'Otro')], default='V', max_length=1, verbose_name='Nacionalidad')),
                ('cedula', models.CharField(max_length=20, verbose_name='Cédula')),
                ('nombres', models.CharField(max_length=150, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=150, verbose_name='Apellidos')),
                ('telefono', models.CharField(blank=True, default='', max_length=30, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Correo electrónico')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('observaciones', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
            ],
            options={
                'verbose_name': 'Registrador civil',
                'verbose_name_plural': 'Registradores civiles',
                'ordering': ['apellidos', 'nombres'],
                'constraints': [models.UniqueConstraint(fields=('nacionalidad', 'cedula'), name='registrador_unico_por_cedula')],
            },
        ),
        migrations.CreateModel(
            name='RegistroCivil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre del registro civil')),
                ('estado', models.CharField(blank=True, default='', max_length=60, verbose_name='Estado')),
                ('municipio', models.CharField(blank=True, default='', max_length=100, verbose_name='Municipio')),
                ('parroquia', models.CharField(blank=True, default='', max_length=100, verbose_name='Parroquia')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('observaciones', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('organizacion', models.ForeignKey(blank=True, help_text='Centro de salud al que está adscrito el registro civil, si aplica.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_civiles', to='seguridad.organizacion', verbose_name='Centro / organización')),
            ],
            options={
                'verbose_name': 'Registro civil',
                'verbose_name_plural': 'Registros civiles',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='DesignacionRegistrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(choices=[('TITULAR', 'Titular'), ('SUPLENTE', 'Suplente'), ('ENCARGADO', 'Encargado')], default='TITULAR', max_length=15, verbose_name='Cargo')),
                ('desde', models.DateField(verbose_name='Vigente desde')),
                ('hasta', models.DateField(blank=True, null=True, verbose_name='Vigente hasta')),
                ('fecha_toma_posesion', models.DateField(blank=True, null=True, verbose_name='Fecha de toma de posesión')),
                ('acta_nombramiento', models.CharField(blank=True, default='', max_length=100, verbose_name='Acta / nombramiento')),
                ('observaciones', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Registrado en')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('registrador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='designaciones', to='registradores.registradorcivil', verbose_name='Registrador civil')),
                ('registro_civil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='designaciones', to='registradores.registrocivil', verbose_name='Registro civil')),
            ],
            options={
                'verbose_name': 'Designación de registrador',
                'verbose_name_plural': 'Designaciones de registradores',
                'ordering': ['-desde', '-id'],
                'constraints': [models.UniqueConstraint(fields=('registro_civil', 'registrador', 'desde'), name='designacion_unica_por_inicio'), models.CheckConstraint(condition=models.Q(('hasta__isnull', True), ('hasta__gte', models.F('desde')), _connector='OR'), name='designacion_vigencia_valida')],
            },
        ),
    ]
