NACIMIENTOS = [
    {
        "id": 1,
        "registro_numero": "NC-2026-000001",
        "lote_id": "LOTE-2026-08-10",
        "fecha_evento": "2026-08-10",
        "hora_nacimiento": "06:40:00",
        "sexo": "M", "sexo_label": "Masculino",
        "peso_gramos": 3450, "talla_cm": "50.0", "edad_gestacional_semanas": 39,
        "tipo_parto": "VAGINAL", "tipo_parto_label": "Vaginal", "tipo_embarazo": "UNICO", "numero_gemelar": None,
        "sitio_nacimiento": "ESTABLECIMIENTO",
        "establecimiento": "Hospital Universitario de Caracas",
        "estado": "Distrito Capital", "municipio": "Libertador", "parroquia": "San José",
        "nacido_vivo": True, "apgar_1m": 8, "apgar_5m": 9,
        "madre_nombres": "María Elena", "madre_apellidos": "González Pérez",
        "madre_cedula": "V-21778945", "madre_edad": 28, "madre_estado_civil": "SOLTERA",
        "padre_nombres": "Luis Alberto", "padre_apellidos": "Ramírez", "padre_cedula": "V-19560214",
        "libro": "1", "folio": 12, "acta": 784,
        "version_cie": "CIE11", "cie10": None, "cie11": 5,
        "cie10_detalle": None,
        "cie11_detalle": {"codigo": "1F4Z", "titulo": "Malaria inespecífica", "nivel": 3, "nivel_label": "Categoría", "requiere_subgrupo": False},
        "creado_en": "2026-08-11T09:00:00Z",
    },
    {
        "id": 2,
        "registro_numero": "NC-2026-000002",
        "lote_id": "LOTE-2026-08-10",
        "fecha_evento": "2026-08-11",
        "hora_nacimiento": "02:15:00",
        "sexo": "F", "sexo_label": "Femenino",
        "peso_gramos": 2980, "talla_cm": "48.5", "edad_gestacional_semanas": 38,
        "tipo_parto": "CESAREA", "tipo_parto_label": "Cesárea", "tipo_embarazo": "GEMELAR", "numero_gemelar": 2,
        "sitio_nacimiento": "ESTABLECIMIENTO",
        "establecimiento": "Maternidad Concepción Palacios",
        "estado": "Distrito Capital", "municipio": "Libertador", "parroquia": "El Recreo",
        "nacido_vivo": True, "apgar_1m": 7, "apgar_5m": 9,
        "madre_nombres": "Ana Gabriela", "madre_apellidos": "Torres",
        "madre_cedula": "V-20345678", "madre_edad": 33, "madre_estado_civil": "CASADA",
        "padre_nombres": "Carlos", "padre_apellidos": "Bustamante", "padre_cedula": "V-18223344",
        "libro": "1", "folio": 3, "acta": 91,
        "version_cie": "CIE11", "cie10": None, "cie11": None,
        "cie10_detalle": None, "cie11_detalle": None,
        "creado_en": "2026-08-11T09:05:00Z",
    },
    {
        "id": 3,
        "registro_numero": "NC-2005-000078",
        "lote_id": "LOTE-HIST-2005",
        "fecha_evento": "2005-06-30",
        "hora_nacimiento": "11:00:00",
        "sexo": "F", "sexo_label": "Femenino",
        "peso_gramos": 3200, "talla_cm": "49.0", "edad_gestacional_semanas": 40,
        "tipo_parto": "VAGINAL", "tipo_parto_label": "Vaginal", "tipo_embarazo": "UNICO", "numero_gemelar": None,
        "sitio_nacimiento": "ESTABLECIMIENTO",
        "establecimiento": "Hospital José María Vargas",
        "estado": "Distrito Capital", "municipio": "Libertador", "parroquia": "La Pastora",
        "nacido_vivo": True, "apgar_1m": 9, "apgar_5m": 10,
        "madre_nombres": "Carmen", "madre_apellidos": "Rojas",
        "madre_cedula": "V-9155667", "madre_edad": 24, "madre_estado_civil": "SOLTERA",
        "padre_nombres": "José", "padre_apellidos": "Mendoza", "padre_cedula": "V-7112345",
        "libro": "2", "folio": 145, "acta": 2930,
        "version_cie": "CIE10", "cie10": 1, "cie11": None,
        "cie10_detalle": {"codigo": "B50", "descripcion": "Paludismo por Plasmodium falciparum"},
        "cie11_detalle": None,
        "creado_en": "2026-08-11T10:00:00Z",
    },
]

DEFUNCIONES = [
    {
        "id": 1,
        "registro_numero": "DEF-2026-000120",
        "lote_id": "LOTE-2026-08-10",
        "fecha_evento": "2026-08-09",
        "hora_defuncion": "14:30:00",
        "fallecido_nombres": "Pedro José", "fallecido_apellidos": "Sánchez", "fallecido_cedula": "V-5454332",
        "sexo": "M", "fecha_nacimiento": "1958-02-14",
        "lugar_defuncion": "ESTABLECIMIENTO",
        "establecimiento": "Hospital Universitario de Caracas",
        "estado": "Distrito Capital", "municipio": "Libertador", "parroquia": "San Bernardino",
        "causa_directa": "Fallo multiorgánico",
        "embarazo_o_puerperio": False, "autopsia": True, "embalsamado": False,
        "certificador_nombres": "Dra. Lucía Fernández", "certificador_cedula": "V-9891234",
        "version_cie": "CIE11", "cie10": None, "cie11": 4,
        "cie10_detalle": None,
        "cie11_detalle": {"codigo": "1F44", "titulo": "Malaria por otras especies de Plasmodium", "nivel": 3, "nivel_label": "Categoría", "requiere_subgrupo": True},
        "creado_en": "2026-08-11T08:00:00Z",
    },
    {
        "id": 2,
        "registro_numero": "DEF-1990-000005",
        "lote_id": "LOTE-HIST-1990",
        "fecha_evento": "1990-11-03",
        "hora_defuncion": "07:45:00",
        "fallecido_nombres": "Rosa Amelia", "fallecido_apellidos": "López", "fallecido_cedula": "V-3200987",
        "sexo": "F", "fecha_nacimiento": "1935-08-25",
        "lugar_defuncion": "DOMICILIO",
        "establecimiento": "",
        "estado": "Distrito Capital", "municipio": "Libertador", "parroquia": "23 de Enero",
        "causa_directa": "Septicemia",
        "embarazo_o_puerperio": False, "autopsia": False, "embalsamado": True,
        "certificador_nombres": "Dr. Manuel Quintero", "certificador_cedula": "V-2811234",
        "version_cie": "CIE10", "cie10": 5, "cie11": None,
        "cie10_detalle": {"codigo": "B54", "descripcion": "Paludismo no especificado"},
        "cie11_detalle": None,
        "creado_en": "2026-08-11T08:15:00Z",
    },
]

FICHAS_VIGILANCIA = [
    {
        "id": 1,
        "codigo_notificacion": "FV-2026-00345",
        "nombre_evento": "Malaria",
        "fecha_notificacion": "2026-08-10",
        "fecha_evento": "2026-08-08",
        "fecha_inicio_sintomas": "2026-08-04",
        "clasificacion": "CONFIRMADO",
        "establecimiento": "Ambulatorio Urbano Tipo II La Florida",
        "estado": "Distrito Capital", "municipio": "Libertador", "parroquia": "La Florida",
        "paciente_nombres": "Miguel", "paciente_apellidos": "Camacho", "paciente_cedula": "V-17889900",
        "sexo": "M", "edad": 41,
        "sintomas": "Fiebre, escalofríos, cefalea",
        "nota": "Gota gruesa positiva",
        "version_cie": "CIE11", "cie10": None, "cie11": 5,
        "cie10_detalle": None,
        "cie11_detalle": {"codigo": "1F4Z", "titulo": "Malaria inespecífica", "nivel": 3, "nivel_label": "Categoría", "requiere_subgrupo": False},
        "creado_en": "2026-08-11T12:00:00Z",
    },
    {
        "id": 2,
        "codigo_notificacion": "FV-2001-00012",
        "nombre_evento": "Malaria",
        "fecha_notificacion": "2001-05-12",
        "fecha_evento": "2001-05-10",
        "fecha_inicio_sintomas": "2001-05-07",
        "clasificacion": "CONFIRMADO",
        "establecimiento": "Centro de Salud El Valle",
        "estado": "Distrito Capital", "municipio": "Libertador", "parroquia": "El Valle",
        "paciente_nombres": "Douglas", "paciente_apellidos": "Parra", "paciente_cedula": "V-6500123",
        "sexo": "M", "edad": 22,
        "sintomas": "Fiebre intermitente",
        "nota": "",
        "version_cie": "CIE10", "cie10": 2, "cie11": None,
        "cie10_detalle": {"codigo": "B51", "descripcion": "Paludismo por Plasmodium vivax"},
        "cie11_detalle": None,
        "creado_en": "2026-08-11T12:05:00Z",
    },
]