# Generated by Django 5.2.17 on 2026-08-12 01:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('codigo', models.CharField(max_length=30, unique=True, verbose_name='Código')),
                ('nivel', models.CharField(choices=[('MINISTERIO', 'Ministerio de Salud'), ('GOBERNACION', 'Gobernación'), ('REGIONAL', 'Dirección Regional'), ('CENTRO', 'Centro de salud')], default='CENTRO', max_length=15, verbose_name='Nivel')),
                ('estado', models.CharField(blank=True, max_length=60, verbose_name='Estado')),
                ('municipio', models.CharField(blank=True, max_length=100, verbose_name='Municipio')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos', to='seguridad.organizacion', verbose_name='Depende de')),
            ],
            options={
                'verbose_name': 'Organización',
                'verbose_name_plural': 'Organizaciones',
                'ordering': ['nivel', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('TRANSCRIPTOR', 'Transcriptor'), ('CODIFICADOR', 'Codificador'), ('EPIDEMIOLOGO', 'Epidemiólogo'), ('DIRECTOR', 'Director')], default='TRANSCRIPTOR', max_length=15, verbose_name='Rol')),
                ('organizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='integrantes', to='seguridad.organizacion', verbose_name='Organización asociada')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de usuario',
                'verbose_name_plural': 'Perfiles de usuarios',
            },
        ),
    ]
