# Generated by Django 5.2.17 on 2026-09-20 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
        ('territorio', '0002_asic'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacion',
            name='asic',
            field=models.ForeignKey(blank=True, help_text='Área de Salud Integral Comunitaria a la que pertenece el centro de salud.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizaciones', to='territorio.asic', verbose_name='ASIC asociado'),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='parroquia',
            field=models.CharField(blank=True, max_length=100, verbose_name='Parroquia'),
        ),
    ]
