# Generated by Django 5.2.17 on 2026-09-24 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0002_organizacion_asic_organizacion_parroquia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('TRANSCRIPTOR', 'Transcriptor'), ('CODIFICADOR', 'Codificador'), ('EPIDEMIOLOGO', 'Epidemiólogo'), ('VIGILANCIA', 'Vigilancia'), ('SECRETARIA', 'Secretaría'), ('DIRECTOR', 'Director')], default='TRANSCRIPTOR', max_length=15, verbose_name='Rol'),
        ),
    ]
