# Generated by Django 5.2.17 on 2026-10-01 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0003_alter_perfil_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('TRANSCRIPTOR', 'Transcriptor'), ('CODIFICADOR', 'Codificador'), ('EPIDEMIOLOGO', 'Epidemiólogo'), ('VIGILANCIA', 'Vigilancia'), ('SECRETARIA', 'Secretaría'), ('DIRECTOR', 'Director'), ('JEFE_UNIDAD', 'Jefe de Unidad')], default='TRANSCRIPTOR', max_length=15, verbose_name='Rol'),
        ),
    ]
