# Generated by Django 5.2.17 on 2026-09-13 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seguridad', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoENO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_evento', models.CharField(max_length=60, unique=True, verbose_name='Código interno')),
                ('nombre', models.CharField(max_length=300, verbose_name='Enfermedad / Evento')),
                ('orden_epi12', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Orden EPI-12')),
                ('orden_epi14', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Orden EPI-14')),
                ('en_epi12', models.BooleanField(default=False, verbose_name='En EPI-12 (morbilidad)')),
                ('en_epi14', models.BooleanField(default=False, verbose_name='En EPI-14 (mortalidad)')),
                ('codigos_cie11', models.CharField(blank=True, max_length=200, verbose_name='Códigos CIE-11')),
                ('codigos_cie10', models.CharField(blank=True, max_length=200, verbose_name='Códigos CIE-10 (si hay mapeo)')),
                ('notificacion', models.CharField(choices=[('INMEDIATA', 'Inmediata'), ('SEMANAL', 'Semanal')], default='SEMANAL', max_length=10, verbose_name='Tipo de notificación')),
                ('grupo', models.CharField(choices=[('TRANSMISIBLES', 'Transmisibles'), ('IRA', 'Infecciones respiratorias agudas'), ('IRS', 'Infecciones respiratorias / síndromes'), ('ITS', 'Infecciones de transmisión sexual'), ('CARGAS', 'Cargas / crónicas no transmisibles'), ('MATERNO_INFANTIL', 'Materno infantil'), ('MICOTICAS', 'Enfermedades micóticas'), ('OTRO', 'Otro')], default='OTRO', max_length=20, verbose_name='Grupo')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Evento ENO',
                'verbose_name_plural': 'Eventos ENO (notificación obligatoria)',
                'ordering': ['orden_epi12', 'orden_epi14', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConsolidadoSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveSmallIntegerField(verbose_name='Año')),
                ('semana', models.PositiveSmallIntegerField(verbose_name='Semana epidemiológica (1-53)')),
                ('tipo', models.CharField(choices=[('MORBILIDAD', 'Morbilidad (EPI-12)'), ('MORTALIDAD', 'Mortalidad (EPI-14)')], max_length=10, verbose_name='Tipo de consolidado')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADO', 'Enviado'), ('CERRADO', 'Cerrado')], default='BORRADOR', max_length=10, verbose_name='Estado')),
                ('origen', models.CharField(choices=[('PROPIO', 'Propio del establecimiento'), ('CONSOLIDADO_SUPERIOR', 'Suma de organizaciones dependientes')], default='PROPIO', max_length=22, verbose_name='Origen')),
                ('enviado_en', models.DateTimeField(blank=True, null=True, verbose_name='Enviado en')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consolidados_semanales', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consolidados_semanales', to='seguridad.organizacion', verbose_name='Organización / establecimiento')),
            ],
            options={
                'verbose_name': 'Consolidado semanal',
                'verbose_name_plural': 'Consolidados semanales',
                'ordering': ['-anio', '-semana', 'tipo'],
            },
        ),
        migrations.CreateModel(
            name='AlertaEpidemia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase', models.CharField(choices=[('ALERTA', 'Situación de alerta'), ('EPIDEMIA', 'Situación de epidemia')], max_length=10, verbose_name='Clase')),
                ('enfermedad', models.CharField(blank=True, max_length=200, verbose_name='Enfermedad')),
                ('casos', models.PositiveIntegerField(default=0, verbose_name='Casos')),
                ('muertes', models.PositiveIntegerField(default=0, verbose_name='Muertes')),
                ('grave', models.BooleanField(default=False, verbose_name='Grave')),
                ('inusitado', models.BooleanField(default=False, verbose_name='Inusitado')),
                ('impacto_nacional', models.BooleanField(default=False, verbose_name='Impacto nacional')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha fin')),
                ('unidad_geografica', models.CharField(blank=True, max_length=200, verbose_name='Unidad geográfica')),
                ('unidad_sanitaria', models.CharField(blank=True, max_length=200, verbose_name='Unidad sanitaria')),
                ('consolidado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_epidemias', to='vigilancia.consolidadosemanal')),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_epidemias', to='vigilancia.eventoeno')),
            ],
            options={
                'verbose_name': 'Alerta / epidemia',
                'verbose_name_plural': 'Alertas / epidemias',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='FilaConsolidado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menor_1_h', models.PositiveIntegerField(default=0, verbose_name='<1 H')),
                ('menor_1_m', models.PositiveIntegerField(default=0, verbose_name='<1 M')),
                ('de_1_4_h', models.PositiveIntegerField(default=0, verbose_name='1-4 H')),
                ('de_1_4_m', models.PositiveIntegerField(default=0, verbose_name='1-4 M')),
                ('de_5_6_h', models.PositiveIntegerField(default=0, verbose_name='5-6 H')),
                ('de_5_6_m', models.PositiveIntegerField(default=0, verbose_name='5-6 M')),
                ('de_7_9_h', models.PositiveIntegerField(default=0, verbose_name='7-9 H')),
                ('de_7_9_m', models.PositiveIntegerField(default=0, verbose_name='7-9 M')),
                ('de_10_11_h', models.PositiveIntegerField(default=0, verbose_name='10-11 H')),
                ('de_10_11_m', models.PositiveIntegerField(default=0, verbose_name='10-11 M')),
                ('de_12_14_h', models.PositiveIntegerField(default=0, verbose_name='12-14 H')),
                ('de_12_14_m', models.PositiveIntegerField(default=0, verbose_name='12-14 M')),
                ('de_15_19_h', models.PositiveIntegerField(default=0, verbose_name='15-19 H')),
                ('de_15_19_m', models.PositiveIntegerField(default=0, verbose_name='15-19 M')),
                ('de_20_24_h', models.PositiveIntegerField(default=0, verbose_name='20-24 H')),
                ('de_20_24_m', models.PositiveIntegerField(default=0, verbose_name='20-24 M')),
                ('de_25_44_h', models.PositiveIntegerField(default=0, verbose_name='25-44 H')),
                ('de_25_44_m', models.PositiveIntegerField(default=0, verbose_name='25-44 M')),
                ('de_45_59_h', models.PositiveIntegerField(default=0, verbose_name='45-59 H')),
                ('de_45_59_m', models.PositiveIntegerField(default=0, verbose_name='45-59 M')),
                ('de_60_64_h', models.PositiveIntegerField(default=0, verbose_name='60-64 H')),
                ('de_60_64_m', models.PositiveIntegerField(default=0, verbose_name='60-64 M')),
                ('de_65_h', models.PositiveIntegerField(default=0, verbose_name='65+ H')),
                ('de_65_m', models.PositiveIntegerField(default=0, verbose_name='65+ M')),
                ('edad_ignorada_h', models.PositiveIntegerField(default=0, verbose_name='Edad ignorada (Hombres)')),
                ('edad_ignorada_m', models.PositiveIntegerField(default=0, verbose_name='Edad ignorada (Mujeres)')),
                ('consolidado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filas', to='vigilancia.consolidadosemanal')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='filas_consolidado', to='vigilancia.eventoeno')),
            ],
            options={
                'verbose_name': 'Fila del consolidado',
                'verbose_name_plural': 'Filas del consolidado',
                'ordering': ['evento__orden_epi12', 'evento__orden_epi14'],
            },
        ),
        migrations.CreateModel(
            name='SituacionEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('QUIMICO', 'Químico'), ('RADIONUCLEAR', 'Radionuclear'), ('EN_ANIMALES', 'En animales'), ('DESASTRE_NATURAL', 'Desastre natural'), ('ALIMENTARIO', 'Alimentario'), ('INFECCIOSO', 'Infeccioso'), ('INDETERMINADO', 'Indeterminado')], max_length=18, verbose_name='Tipo de evento')),
                ('comunidad', models.CharField(blank=True, max_length=200, verbose_name='Comunidad')),
                ('casos', models.PositiveIntegerField(default=0, verbose_name='Casos')),
                ('muertes', models.PositiveIntegerField(default=0, verbose_name='Muertes')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción del evento')),
                ('medidas_tomadas', models.TextField(blank=True, verbose_name='Medidas tomadas')),
                ('consolidado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='situaciones_especiales', to='vigilancia.consolidadosemanal')),
            ],
            options={
                'verbose_name': 'Situación especial',
                'verbose_name_plural': 'Situaciones especiales',
                'ordering': ['-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='consolidadosemanal',
            constraint=models.UniqueConstraint(fields=('organizacion', 'anio', 'semana', 'tipo'), name='uq_consolidado_semanal'),
        ),
        migrations.AddConstraint(
            model_name='filaconsolidado',
            constraint=models.UniqueConstraint(fields=('consolidado', 'evento'), name='uq_fila_consolidado_evento'),
        ),
    ]
