# Generated by Django 5.2.17 on 2026-09-24 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0002_organizacion_asic_organizacion_parroquia'),
        ('vigilancia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consolidadosemanal',
            name='legacy_documento',
            field=models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Documento legacy de origen'),
        ),
        migrations.AddField(
            model_name='consolidadosemanal',
            name='legacy_tabla',
            field=models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Tabla legacy de origen'),
        ),
        migrations.CreateModel(
            name='ConsolidadoEpi15',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveSmallIntegerField(verbose_name='Año')),
                ('semana', models.PositiveSmallIntegerField(verbose_name='Semana epidemiológica (1-53)')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADO', 'Enviado'), ('CERRADO', 'Cerrado')], default='BORRADOR', max_length=10, verbose_name='Estado')),
                ('origen', models.CharField(choices=[('PROPIO', 'Propio del establecimiento'), ('CONSOLIDADO_SUPERIOR', 'Suma de organizaciones dependientes')], default='PROPIO', max_length=22, verbose_name='Origen')),
                ('legacy_tabla', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Tabla legacy de origen')),
                ('legacy_documento', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Documento legacy de origen')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consolidados_epi15', to='seguridad.organizacion', verbose_name='Organización / establecimiento')),
            ],
            options={
                'verbose_name': 'Consolidado semanal EPI-15',
                'verbose_name_plural': 'Consolidados semanales EPI-15',
                'ordering': ['-anio', '-semana'],
            },
        ),
        migrations.CreateModel(
            name='FilaEpi15',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.PositiveBigIntegerField(verbose_name='ID legacy (INFORME_EPI)')),
                ('codigo_legacy', models.CharField(blank=True, max_length=20, verbose_name='Código legacy')),
                ('nombre_legacy', models.CharField(blank=True, max_length=200, verbose_name='Nombre legacy')),
                ('casosp', models.PositiveIntegerField(default=0, verbose_name='Casos primeras consultas')),
                ('casoss', models.PositiveIntegerField(default=0, verbose_name='Casos subsiguientes')),
                ('casosx', models.PositiveIntegerField(default=0, verbose_name='Casos (columna X)')),
                ('consolidado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filas', to='vigilancia.consolidadoepi15')),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filas_epi15', to='vigilancia.eventoeno')),
            ],
            options={
                'verbose_name': 'Fila del EPI-15',
                'verbose_name_plural': 'Filas del EPI-15',
                'ordering': ['nombre_legacy'],
            },
        ),
        migrations.AddConstraint(
            model_name='consolidadoepi15',
            constraint=models.UniqueConstraint(fields=('organizacion', 'anio', 'semana'), name='uq_consolidado_epi15'),
        ),
        migrations.AddConstraint(
            model_name='filaepi15',
            constraint=models.UniqueConstraint(fields=('consolidado', 'legacy_id'), name='uq_fila_epi15_legacy'),
        ),
    ]
