# Generated by Django 5.2.17 on 2026-08-12 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DivisionTerritorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=120, verbose_name='Nombre')),
                ('codigo', models.CharField(blank=True, max_length=20, verbose_name='Código')),
                ('nivel', models.CharField(choices=[('ESTADO', 'Estado'), ('MUNICIPIO', 'Municipio'), ('PARROQUIA', 'Parroquia'), ('COMUNIDAD', 'Comunidad')], db_index=True, max_length=12, verbose_name='Nivel')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos', to='territorio.divisionterritorial', verbose_name='Depende de')),
            ],
            options={
                'verbose_name': 'División territorial',
                'verbose_name_plural': 'División territorial',
                'ordering': ['nivel', 'nombre'],
                'constraints': [models.UniqueConstraint(fields=('nivel', 'nombre', 'padre'), name='territorio_unico_por_padre')],
            },
        ),
    ]
