# Generated by Django 5.2.17 on 2026-09-20 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territorio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ASIC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del ASIC')),
                ('codigo', models.CharField(max_length=30, unique=True, verbose_name='Código')),
                ('direccion', models.CharField(blank=True, max_length=300, verbose_name='Dirección de la sede')),
                ('responsable', models.CharField(blank=True, max_length=200, verbose_name='Responsable')),
                ('telefono', models.CharField(blank=True, max_length=40, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo')),
                ('establecimientos_adscritos', models.PositiveSmallIntegerField(default=0, help_text='Consultorios populares, ambulatorios, CDI/CRI y otros de la red del ASIC.', verbose_name='Establecimientos adscritos')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('parroquia', models.ForeignKey(blank=True, help_text='Parroquia donde se ubica la sede del área de salud.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asics', to='territorio.divisionterritorial', verbose_name='Parroquia sede')),
            ],
            options={
                'verbose_name': 'ASIC',
                'verbose_name_plural': 'ASIC',
                'ordering': ['nombre'],
            },
        ),
    ]
