# Generated by Django 5.2.17 on 2026-09-24 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territorio', '0002_asic'),
    ]

    operations = [
        migrations.AddField(
            model_name='asic',
            name='comunidades',
            field=models.ManyToManyField(blank=True, help_text='Comunidades (nivel COMUNIDAD) que integran el área de salud integral.', related_name='asics_territoriales', to='territorio.divisionterritorial', verbose_name='Comunidades del territorio'),
        ),
    ]
